<?php
    class empresa{
        public $bairro='BONSUCESSO';
        public $cep='21041-040';
        public $cidade='RIO DE JANEIRO (RJ)';
        public $cnae='2621300';
        public $cnae_municipal; 
        public $cnpj='39.062.831/0004-76';
        public $codigo_empresa='740225718';
        public $codigo_pais='1058';
        public $complemento='LOJA B';
        public $ecd_codigo_cadastral; 
        public $ecd_codigo_instituicao_responsavel; 
        public $efd_atividade_industrial; 
        public $efd_perfil_arquivo_fiscal; 
        public $email='comercial@lojascom.com.br';
        public $endereco='AV NOVA YORK';
        public $endereco_numero='138';
        public $estado='RJ';
        public $fax_ddd; 
        public $fax_numero; 
        public $gera_nfse='N';
        public $inativa='N';
        public $inscricao_estadual='87030270';
        public $inscricao_municipal; 
        public $inscricao_suframa; 
        public $logradouro;
        public $nome_fantasia='LojasCom';
        public $optante_simples_nacional='N';
        public $pdv_sincr_analitica='S';
        public $razao_social='SHEKINAH TECHNOLOGY';
        public $regime_tributario='4';
        public $sped_codigo_criterio_escrituracao; 
        public $sped_codigo_incidencia_tributaria; 
        public $sped_codigo_indicador_apropriacao_credito; 
        public $sped_codigo_tipo_atividade;
        public $sped_codigo_tipo_contribuicao; 
        public $sped_cpf_contador;
        public $sped_crc_contador;
        public $sped_email_contador; 
        public $sped_junta_comercial; 
        public $sped_matriz;
        public $sped_natureza_pessoa_juridica;
        public $sped_nome_contador;
        public $sped_registro_junta_comercial;
        public $sped_usa_contabilidade_terceirizada;
        public $telefone1_ddd='21';
        public $telefone1_numero='2260-3007';
        public $telefone2_ddd; 
        public $telefone2_numero; 
        public $website='www.lojascom.com.br';
    }
?>