<!DOCTYPE html>
<html lang="pt-br">
    <head>
    <?php 
        include 'menu.php';
        include 'relatorio.php';
    ?> 
    </head>
    <body>
        <table id="tPed">
                <caption>Pedidos Pendentes</caption>
            
            <tr><td class="ce">Cliente</td><td class="cd">Cesar Augustus</td></tr>
            <tr><td class="ce">Cod. Produto</td><td class="cd"> 25145</td></tr>
            <tr><td class="ce">Desc. Produto</td><td class="cd"> Mouse C3Tech</td></tr>
            <tr><td class="ce">Memória Interna</td><td class="cd"> 12GB</td></tr>
            </table>

    </body>
</html>