<?php 
 class CRUDProduto extends Dao{
   public function insert(modelProduto $modelProduto){
                date_default_timezone_set("Brazil/East");
                $now = mktime (date('H'), date('i'), date('s'), date("m")  , date("d"), date("Y"));
                $modelProduto->setid(null);
                $modelProduto->setexcluido(0);
                $modelProduto->setcriado($now);  
                $sql=$this->criaTabela('tb_produto');
                $this->execute2($sql, $modelProduto);   
                //$this->execute2('ALTER TABLE `tb_cliente` ADD UNIQUE(`cnpj_cpf`)', $modelProduto);
                $sql = 'INSERT INTO tb_produto (`aliquota_cofins`,`aliquota_ibpt`,`aliquota_icms`,`aliquota_pis`,`altura`,`bloqueado`,`cest`,`cfop`,`codInt_familia`,`codigo`,`codigo_familia`,`codigo_produto`,`codigo_produto_integracao`,`csosn_icms`,`cst_cofins`,`cst_icms`,`cst_pis`,`dadosIbpt`,`aliqEstadual`,`aliqFederal`,`aliqMunicipal`,`chave`,`fonte`,`valido_ate`,`valido_de`,`versao`,`descr_detalhada`,`descricao`,`descricao_familia`,`dias_crossdocking`,`dias_garantia`,`ean`,`estoque_minimo`,`imagens`,`url_imagem`,`importado_api`,`inativo`,`largura`,`marca`,`ncm`,`obs_internas`,`peso_bruto`,`peso_liq`,`profundidade`,`quantidade_estoque`,`recomendacoes_fiscais`,`cupom_fiscal`,`id_cest`,`id_preco_tabelado`,`market_place`,`origem_mercadoria`,`red_base_icms`,`tipoItem`,`unidade`,`valor_unitario`,`id`,`excluido`,`criado`) VALUES (:aliquota_cofins,:aliquota_ibpt,:aliquota_icms,:aliquota_pis,:altura,:bloqueado,:cest,:cfop,:codInt_familia,:codigo,:codigo_familia,:codigo_produto,:codigo_produto_integracao,:csosn_icms,:cst_cofins,:cst_icms,:cst_pis,:dadosIbpt,:aliqEstadual,:aliqFederal,:aliqMunicipal,:chave,:fonte,:valido_ate,:valido_de,:versao,:descr_detalhada,:descricao,:descricao_familia,:dias_crossdocking,:dias_garantia,:ean,:estoque_minimo,:imagens,:url_imagem,:importado_api,:inativo,:largura,:marca,:ncm,:obs_internas,:peso_bruto,:peso_liq,:profundidade,:quantidade_estoque,:recomendacoes_fiscais,:cupom_fiscal,:id_cest,:id_preco_tabelado,:market_place,:origem_mercadoria,:red_base_icms,:tipoItem,:unidade,:valor_unitario,:id,:excluido,:criado)';
	$search = new ProdutoSearchCriteria();
                $search->settabela($modelProduto->gettabela());
                return $this->execute2($sql, $modelProduto);
                }
   public function update(modelProduto $modelProduto){
                date_default_timezone_set("Brazil/East");
                $now = mktime (date("H"), date("i"), date("s"), date("m")  , date("d"), date("Y"));
                $modelProduto->setmodificado($now);
                $sql = 'UPDATE tb_produto SET id=:id,criado=:criado,modificado=:modificado, aliquota_cofins = :aliquota_cofins, aliquota_ibpt = :aliquota_ibpt, aliquota_icms = :aliquota_icms, aliquota_pis = :aliquota_pis, altura = :altura, bloqueado = :bloqueado, cest = :cest, cfop = :cfop, codInt_familia = :codInt_familia, codigo = :codigo, codigo_familia = :codigo_familia, codigo_produto = :codigo_produto, codigo_produto_integracao = :codigo_produto_integracao, csosn_icms = :csosn_icms, cst_cofins = :cst_cofins, cst_icms = :cst_icms, cst_pis = :cst_pis, dadosIbpt = :dadosIbpt, aliqEstadual = :aliqEstadual, aliqFederal = :aliqFederal, aliqMunicipal = :aliqMunicipal, chave = :chave, fonte = :fonte, valido_ate = :valido_ate, valido_de = :valido_de, versao = :versao, descr_detalhada = :descr_detalhada, descricao = :descricao, descricao_familia = :descricao_familia, dias_crossdocking = :dias_crossdocking, dias_garantia = :dias_garantia, ean = :ean, estoque_minimo = :estoque_minimo, imagens = :imagens, url_imagem = :url_imagem, importado_api = :importado_api, inativo = :inativo, largura = :largura, marca = :marca, ncm = :ncm, obs_internas = :obs_internas, peso_bruto = :peso_bruto, peso_liq = :peso_liq, profundidade = :profundidade, quantidade_estoque = :quantidade_estoque, recomendacoes_fiscais = :recomendacoes_fiscais, cupom_fiscal = :cupom_fiscal, id_cest = :id_cest, id_preco_tabelado = :id_preco_tabelado, market_place = :market_place, origem_mercadoria = :origem_mercadoria, red_base_icms = :red_base_icms, tipoItem = :tipoItem, unidade = :unidade, valor_unitario = :valor_unitario WHERE id = :id ';
                    return $this->execute2($sql, $modelProduto);
           }
    public function criaTabela($tabela){
                        $sql="CREATE TABLE IF NOT EXISTS tb_produto ( `id` INT(5) NOT NULL AUTO_INCREMENT , `criado` INT(100) NULL,`aliquota_cofins` varchar(100) NULL,`aliquota_ibpt` varchar(100) NULL,`aliquota_icms` varchar(100) NULL,`aliquota_pis` varchar(100) NULL,`altura` varchar(100) NULL,`bloqueado` varchar(100) NULL,`cest` varchar(100) NULL,`cfop` varchar(100) NULL,`codInt_familia` varchar(100) NULL,`codigo` varchar(100) NULL,`codigo_familia` varchar(100) NULL,`codigo_produto` varchar(100) NULL,`codigo_produto_integracao` varchar(100) NULL,`csosn_icms` varchar(100) NULL,`cst_cofins` varchar(100) NULL,`cst_icms` varchar(100) NULL,`cst_pis` varchar(100) NULL,`dadosIbpt` varchar(100) NULL,`aliqEstadual` varchar(100) NULL,`aliqFederal` varchar(100) NULL,`aliqMunicipal` varchar(100) NULL,`chave` varchar(100) NULL,`fonte` varchar(100) NULL,`valido_ate` varchar(100) NULL,`valido_de` varchar(100) NULL,`versao` varchar(100) NULL,`descr_detalhada` varchar(100) NULL,`descricao` varchar(100) NULL,`descricao_familia` varchar(100) NULL,`dias_crossdocking` varchar(100) NULL,`dias_garantia` varchar(100) NULL,`ean` varchar(100) NULL,`estoque_minimo` varchar(100) NULL,`imagens` varchar(100) NULL,`url_imagem` varchar(100) NULL,`importado_api` varchar(100) NULL,`inativo` varchar(100) NULL,`largura` varchar(100) NULL,`marca` varchar(100) NULL,`ncm` varchar(100) NULL,`obs_internas` varchar(100) NULL,`peso_bruto` varchar(100) NULL,`peso_liq` varchar(100) NULL,`profundidade` varchar(100) NULL,`quantidade_estoque` varchar(100) NULL,`recomendacoes_fiscais` varchar(100) NULL,`cupom_fiscal` varchar(100) NULL,`id_cest` varchar(100) NULL,`id_preco_tabelado` varchar(100) NULL,`market_place` varchar(100) NULL,`origem_mercadoria` varchar(100) NULL,`red_base_icms` varchar(100) NULL,`tipoItem` varchar(100) NULL,`unidade` varchar(100) NULL,`valor_unitario` varchar(100) NULL, `excluido` ENUM('0','1') NOT NULL DEFAULT '0', PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci";
                return $sql;
                }
  public function getParams(modelProduto $modelProduto){
        $params = array(':id'=>$modelProduto->getid(),':excluido'=>$modelProduto->getexcluido(),':criado'=>$modelProduto->getcriado(),':aliquota_cofins'=>$modelProduto->getaliquota_cofins(),':aliquota_ibpt'=>$modelProduto->getaliquota_ibpt(),':aliquota_icms'=>$modelProduto->getaliquota_icms(),':aliquota_pis'=>$modelProduto->getaliquota_pis(),':altura'=>$modelProduto->getaltura(),':bloqueado'=>$modelProduto->getbloqueado(),':cest'=>$modelProduto->getcest(),':cfop'=>$modelProduto->getcfop(),':codInt_familia'=>$modelProduto->getcodInt_familia(),':codigo'=>$modelProduto->getcodigo(),':codigo_familia'=>$modelProduto->getcodigo_familia(),':codigo_produto'=>$modelProduto->getcodigo_produto(),':codigo_produto_integracao'=>$modelProduto->getcodigo_produto_integracao(),':csosn_icms'=>$modelProduto->getcsosn_icms(),':cst_cofins'=>$modelProduto->getcst_cofins(),':cst_icms'=>$modelProduto->getcst_icms(),':cst_pis'=>$modelProduto->getcst_pis(),':dadosIbpt'=>$modelProduto->getdadosIbpt(),':aliqEstadual'=>$modelProduto->getaliqEstadual(),':aliqFederal'=>$modelProduto->getaliqFederal(),':aliqMunicipal'=>$modelProduto->getaliqMunicipal(),':chave'=>$modelProduto->getchave(),':fonte'=>$modelProduto->getfonte(),':valido_ate'=>$modelProduto->getvalido_ate(),':valido_de'=>$modelProduto->getvalido_de(),':versao'=>$modelProduto->getversao(),':descr_detalhada'=>$modelProduto->getdescr_detalhada(),':descricao'=>$modelProduto->getdescricao(),':descricao_familia'=>$modelProduto->getdescricao_familia(),':dias_crossdocking'=>$modelProduto->getdias_crossdocking(),':dias_garantia'=>$modelProduto->getdias_garantia(),':ean'=>$modelProduto->getean(),':estoque_minimo'=>$modelProduto->getestoque_minimo(),':imagens'=>$modelProduto->getimagens(),':url_imagem'=>$modelProduto->geturl_imagem(),':importado_api'=>$modelProduto->getimportado_api(),':inativo'=>$modelProduto->getinativo(),':largura'=>$modelProduto->getlargura(),':marca'=>$modelProduto->getmarca(),':ncm'=>$modelProduto->getncm(),':obs_internas'=>$modelProduto->getobs_internas(),':peso_bruto'=>$modelProduto->getpeso_bruto(),':peso_liq'=>$modelProduto->getpeso_liq(),':profundidade'=>$modelProduto->getprofundidade(),':quantidade_estoque'=>$modelProduto->getquantidade_estoque(),':recomendacoes_fiscais'=>$modelProduto->getrecomendacoes_fiscais(),':cupom_fiscal'=>$modelProduto->getcupom_fiscal(),':id_cest'=>$modelProduto->getid_cest(),':id_preco_tabelado'=>$modelProduto->getid_preco_tabelado(),':market_place'=>$modelProduto->getmarket_place(),':origem_mercadoria'=>$modelProduto->getorigem_mercadoria(),':red_base_icms'=>$modelProduto->getred_base_icms(),':tipoItem'=>$modelProduto->gettipoItem(),':unidade'=>$modelProduto->getunidade(),':valor_unitario'=>$modelProduto->getvalor_unitario(), );
	 return $params;
   }
}