var OMIE_APP_KEY = '3303943460';
var OMIE_APP_SECRET = '8edb08391b6af27936d3daf0ca8aa07d';

var XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;
var ClientesCadastroJsonClient=function(){
	this._EndPoint="http://app.omie.com.br/api/v1/geral/clientes/";
	this._Call=function(method,param,cb){
		var server= new XMLHttpRequest();
		server.open("POST",this._EndPoint,cb!=null);
		server.setRequestHeader("Content-Type","application/json");
		var req=JSON.stringify({call:method,app_key:OMIE_APP_KEY,app_secret:OMIE_APP_SECRET,param:(param)?param:[]});
		if(cb){
			server.onreadystatechange=this._EndCall;
			server.cb=cb;
			server.send(req);
			return server;
		}else{
			server.send(req);
			var res=JSON.parse(server.responseText);
			delete(server);
			return res;
		}
	};
	this._EndCall=function(e){
		var server=this;
		if(server.readyState!=4)
			return;
		if(server.status!=200)
			throw(new Exception("AJAX error "+server.status+": "+server.statusText));
		server.cb(JSON.parse(server.responseText));
		server.cb=null;
		delete(server);
	};
	this.IncluirCliente=function(
		clientes_cadastro,
		_cb
	){
		return this._Call(
			"IncluirCliente",
			[
			clientes_cadastro
			],
			(_cb)?_cb:null
		);
	};
	this.AlterarCliente=function(
		clientes_cadastro,
		_cb
	){
		return this._Call(
			"AlterarCliente",
			[
			clientes_cadastro
			],
			(_cb)?_cb:null
		);
	};
	this.ExcluirCliente=function(
		clientes_cadastro_chave,
		_cb
	){
		return this._Call(
			"ExcluirCliente",
			[
			clientes_cadastro_chave
			],
			(_cb)?_cb:null
		);
	};
	this.ConsultarCliente=function(
		clientes_cadastro_chave,
		_cb
	){
		return this._Call(
			"ConsultarCliente",
			[
			clientes_cadastro_chave
			],
			(_cb)?_cb:null
		);
	};
	this.ListarClientes=function(
		clientes_list_request,
		_cb
	){
		return this._Call(
			"ListarClientes",
			[
			clientes_list_request
			],
			(_cb)?_cb:null
		);
	};
	this.ListarClientesResumido=function(
		clientes_list_request,
		_cb
	){
		return this._Call(
			"ListarClientesResumido",
			[
			clientes_list_request
			],
			(_cb)?_cb:null
		);
	};
	this.IncluirClientesPorLote=function(
		clientes_lote_request,
		_cb
	){
		return this._Call(
			"IncluirClientesPorLote",
			[
			clientes_lote_request
			],
			(_cb)?_cb:null
		);
	};
	this.UpsertCliente=function(
		clientes_cadastro,
		_cb
	){
		return this._Call(
			"UpsertCliente",
			[
			clientes_cadastro
			],
			(_cb)?_cb:null
		);
	};
	this.UpsertClientesPorLote=function(
		clientes_lote_request,
		_cb
	){
		return this._Call(
			"UpsertClientesPorLote",
			[
			clientes_lote_request
			],
			(_cb)?_cb:null
		);
	};
	this.AssociarCodIntCliente=function(
		clientes_cadastro_chave,
		_cb
	){
		return this._Call(
			"AssociarCodIntCliente",
			[
			clientes_cadastro_chave
			],
			(_cb)?_cb:null
		);
	};
	this.clientes_cadastro=function(){
		this.codigo_cliente_omie=null;
		this.codigo_cliente_integracao=null;
		this.razao_social=null;
		this.cnpj_cpf=null;
		this.nome_fantasia=null;
		this.telefone1_ddd=null;
		this.telefone1_numero=null;
		this.contato=null;
		this.endereco=null;
		this.endereco_numero=null;
		this.bairro=null;
		this.complemento=null;
		this.estado=null;
		this.cidade=null;
		this.cep=null;
		this.codigo_pais=null;
		this.telefone2_ddd=null;
		this.telefone2_numero=null;
		this.fax_ddd=null;
		this.fax_numero=null;
		this.email=null;
		this.homepage=null;
		this.inscricao_estadual=null;
		this.inscricao_municipal=null;
		this.inscricao_suframa=null;
		this.optante_simples_nacional=null;
		this.tipo_atividade=null;
		this.cnae=null;
		this.produtor_rural=null;
		this.contribuinte=null;
		this.observacao=null;
		this.recomendacao_atraso=null;
		this.tags=null;
		this.info=null;
		this.pessoa_fisica=null;
		this.exterior=null;
		this.logradouro=null;
		this.importado_api=null;
		this.bloqueado=null;
		this.cidade_ibge=null;
	};
	this.tags=function(){
		this.tag=null;
	};
	this.info=function(){
		this.dInc=null;
		this.hInc=null;
		this.uInc=null;
		this.dAlt=null;
		this.hAlt=null;
		this.uAlt=null;
		this.cImpAPI=null;
	};
	this.clientes_cadastro_chave=function(){
		this.codigo_cliente_omie=null;
		this.codigo_cliente_integracao=null;
	};
	this.clientes_cadastro_resumido=function(){
		this.codigo_cliente=null;
		this.codigo_cliente_integracao=null;
		this.razao_social=null;
		this.nome_fantasia=null;
		this.cnpj_cpf=null;
	};
	this.clientes_list_request=function(){
		this.pagina=null;
		this.registros_por_pagina=null;
		this.apenas_importado_api=null;
		this.ordenar_por=null;
		this.ordem_decrescente=null;
		this.filtrar_por_data_de=null;
		this.filtrar_por_data_ate=null;
		this.filtrar_apenas_inclusao=null;
		this.filtrar_apenas_alteracao=null;
		this.clientesFiltro=null;
		this.clientesPorCodigo=null;
		this.ordem_descrescente=null;
	};
	this.clientesFiltro=function(){
		this.codigo_cliente_omie=null;
		this.codigo_cliente_integracao=null;
		this.cnpj_cpf=null;
		this.razao_social=null;
		this.nome_fantasia=null;
		this.endereco=null;
		this.bairro=null;
		this.cidade=null;
		this.estado=null;
		this.cep=null;
		this.contato=null;
		this.email=null;
		this.homepage=null;
		this.inscricao_municipal=null;
		this.inscricao_estadual=null;
		this.inscricao_suframa=null;
		this.pessoa_fisica=null;
		this.optante_simples_nacional=null;
	};
	this.clientesPorCodigo=function(){
		this.codigo_cliente_omie=null;
		this.codigo_cliente_integracao=null;
	};
	this.clientes_list_response=function(){
		this.pagina=null;
		this.total_de_paginas=null;
		this.registros=null;
		this.total_de_registros=null;
		this.clientes_cadastro_resumido=null;
	};
	this.clientes_listfull_response=function(){
		this.pagina=null;
		this.total_de_paginas=null;
		this.registros=null;
		this.total_de_registros=null;
		this.clientes_cadastro=null;
	};
	this.clientes_lote_request=function(){
		this.lote=null;
		this.clientes_cadastro=null;
	};
	this.clientes_lote_response=function(){
		this.lote=null;
		this.codigo_status=null;
		this.descricao_status=null;
	};
	this.clientes_status=function(){
		this.codigo_cliente_omie=null;
		this.codigo_cliente_integracao=null;
		this.codigo_status=null;
		this.descricao_status=null;
	};
	this.omie_fail=function(){
		this.code=null;
		this.description=null;
		this.referer=null;
		this.fatal=null;
	};
};
module.exports = ClientesCadastroJsonClient;