<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt-br" lang="pt-br">
<head>
    <title>EMQDesenv - Aplicações</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link href="https://fonts.googleapis.com/css?family=Lovers+Quarrel|Miltonian+Tattoo|Sriracha" rel="stylesheet" /> 
    <link rel="shortcut icon" href="emqdesenv.ico" type="image/x-icon" />
    <meta name="description" content="emqdesenv - Aplicações" />
    <meta name="keywords" content="sistemas, PHP" />
    <meta name="author" content="Edmilson Messias Quintino" />

    <link href="css/style.css" rel="stylesheet" type="text/css" />
    <link href="css/layout.css" rel="stylesheet" type="text/css" />
    
    <script type="text/javascript" src="../web/js/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="../web/js/ClientesCadastroJsonClient.js"></script>
    
    <script>
        $(document).ready(function(){
            $('#sair img').mouseover(function(){
                $(this).css({
                    cursor:'pointer'
                })
            })
            $('#sair img').click(function(){
                $(location).attr('href','../web/sair.php');
            })
            $('#flashes').fadeOut(2000,function(){
                $(this).hide('slow');
            })
        })
    </script>
    <style>
        #ico img{
            position: absolute;
            left: 10px;
            height: 40px;
            background: none;
        }
        #sair img{
            float: right;
        }
        .pagina{
            float: right;
            margin-right: 10px;
            text-transform: uppercase;
        }
        .vaivem{
            float: left;
            margin-top: 5px;
            margin-left: -140px;
            //border: solid red;
        }
        .vaivem:hover{
            cursor: pointer;
        }
        .pagina, .mGeral{
            margin-top: 5px;
            font-size: 15px;
            text-shadow: 4px 4px 4px white;
        }
        .mGeral{
            float: left;
            margin: 0px 100px;
            padding: 6px 20px;
            height: 20px;
            //border: solid green;
        }
        .mGeral ul li{
            display: inline;
            padding: 7px 10px;
        }
        .mGeral li:hover{
            cursor: pointer;
            background: #4e9bae;
            color: white;
        }
        .empresa{
            font-size: 15px;
            margin-right: 50px;
            float: right;
            text-transform: uppercase;
            background: #4e9bae;
            color: white;
            text-shadow: 2px 2px 2px black;
            padding: 5px 13px;
        }
    </style>
</head>
<body id="page">
    <div id="main">
        <!-- header -->
        <div id="header">
            <div id="ico"><img src='../web/img/logo.png' title='EMQDesenv' /></div>
            <div class="mGeral"></div>
            <div class="vaivem"></div>
            <div class="pagina"><?= $pagina ?></div>
            <div class="empresa"><?= $_COOKIE['nomeEmpresa'].' - CNPJ: '.$_COOKIE['cnpj']  ?></div>
        </div>
        <span id="sair"><img src="../web/img/sair.png" title="Sair" height="28px" /></span>
        <!-- content -->
        <div id="content">
            <div class="wrapper">
                <!--<div class="col-1">
                    <div class="box">
                        <div class="inner">
                            <img src='emqdesenv.ico' />
                            <ul class="list">
                                <li><span><a href="<?php //echo Utils::createLink('cliente'); ?>" ><img src="img/clientes.png" alt="" title="Cadastro de Clientes" class="icon" />Clientes</a></span></li>
                                <li><span><a href="<?php //echo Utils::createLink('produto'); ?>" ><img src="img/produtos.png" alt="" title="Cadastro de Produtos" class="icon" />Produtos</a></span></li>
                                <li><span><a href="<?php //echo Utils::createLink('pedido'); ?>" ><img src="img/pedidos.png" alt="" title="Pré-Venda" class="icon" />Pré-Venda</a></span></li>
                            </ul>
                        </div>
                    </div>
                </div>-->
                <div class="col-2">
                    <div class="indent">
                        <?php if ($flashes): ?>
                            <ul id="flashes">
                            <?php foreach ($flashes as $flash): ?>
                                <li><?php echo $flash; ?></li>
                            <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                        <?php require $template; ?>
                    </div>
                </div>
            </div>
        </div>
        <!-- footer -->
        <div id="footer">
            <div class="indent">
                <div class="fleft"><a href="">T.I.</a>, 2018 &copy; Copyright, All rights reserved</div>
            </div>
        </div>
    </div>
</body>
</html>