<style>
    .quad1 iframe{
        //border: solid red;
        float: left;
    }
    .quad2 iframe{
        //border: solid black;
        float: right;
    }
    .quad3 iframe{
        //border: solid green;
        clear: left;
        float: left;
    }
    .quad4 iframe{
        //border: solid blue;
        clear: right;
        float: right;
    }
    .quad1 iframe, .quad2 iframe, .quad3 iframe, .quad4 iframe{
        width: 512px;
        height: 312px;
        border: none;
    }
    .quad3, .quad4{
        margin-top: 12px;
    }
</style>
<?php
    include '../model/ClientesCadastroJsonClient.php';
?>
<div class=conteudo>
    <div class=quad1><iframe src="../paginas/cliente.php?act=atualiza"></iframe></div>
    <div class=quad2><iframe></iframe></div>
    <div class=quad3><iframe></iframe></div>
    <div class=quad4><iframe></iframe></div>
</div>
