<script>
    $(document).ready(function(){
        $('#saldo').css({
            float:'right',
            position: 'relative',
            top: '-50px'
        })
        $('.botao').css({
            float: 'right',
            marginRight: '20px'
        })
        $('.botao input').css({
            borderRadius: '0 0 5px 5px',
            fontWeight: '600',
            backgroundColor: '#63a9c1',
            color: '#111f46',
            padding: '1px 4px'
        })
        $('form').css({
            width: '710px'
        })
        $('table tr:odd').css({
            background: '#ccc'
        })
        $('td img').click(function(){
            if($(this).attr('title')=='Exclui'){
                var razao=$(this).attr('razao');
                var confirma=confirm('Confirma Exclusão de "'+razao+'"');
                if(confirma){
                    var codigo=$(this).attr('codigo');
                    $(location).attr('href','index.php?pagina=cliente&act=excl&codigo='+codigo+'')
                }
            }else if($(this).attr('title')=='Altera'){
                var codigo=$(this).attr('codigo');
                $(location).attr('href','index.php?pagina=cliente&act=alt&omie='+codigo+'')
            }
        })
        $('.procura img').mouseover(function(){
            $(this).css('cursor','pointer')
        })
        $('.procura').keyup(function(e){
              var code = e.which;
              if(code==13)e.preventDefault();
              if(code==13||e.keyCode==13){
                  var codigo=$('.procura :input').val();
                  if(codigo){
                    $(location).attr('href','index.php?pagina=cliente&act=cons&codigo='+codigo+'')
                  }
              } 
        })
        $('.procura img').click(function(){
            var codigo=$('.procura :input').val();
              if(codigo){
                $(location).attr('href','index.php?pagina=cliente&act=cons&codigo='+codigo+'')
              }
        })
        
        if(seleciona!=1){
            $('.razaosocial').mouseover(function(){
                $(this).css('cursor','pointer')
                $(this).attr('title','dê um duplo clique para ver detalhes.')
            })
            $('.razaosocial').dblclick(function(){
                var codigo=$(this).attr('linha');
                $(location).attr('href','index.php?pagina=cliente&act=cons&omie='+codigo+'')
            })
        }else{
            $('.razaosocial').css({
               background: 'white'
            })
            $('.razaosocial td').css({
                borderBottom: '1px solid #ccc'
            })
            $('.razaosocial').mouseover(function(){
                $(this).css('cursor','pointer')
                $(this).css('background','silver')
                $(this).mouseleave(function(){
                    $('.razaosocial').css('background','white')
                })
                $(this).click(function(){
                    var codigo_cliente=$(this).attr('linha');
                    var razao=$(this).attr('razao');
                    var cnpj_cpf=$(this).attr('cnpj_cpf');
                    var contato=$(this).attr('contato');
                    var email=$(this).attr('email');
                    /*if(email.indexOf('Undefined') != '-1'){
                        alert('Este cliente não possui e-mail');
                        die;
                    }*/
                    $(location).attr('href','index.php?pagina=pedido&act=cad&codigo_cliente='+codigo_cliente+'&razao='+razao+'&cnpj_cpf='+cnpj_cpf+'&contato='+contato+'&email='+email+'')
                })
            })
        }      
        $(':submit').click(function(){
            var arr=new Array();
            $(':input').each(function(){
                arr.push($(this).attr('name'));          
            })
        }) 
        $('.pagina').text('CLIENTE')
        $(".procura2 input").on("keyup", function(){
            var value = $(this).val().toLowerCase();
            $(".listaCliente .tudo").filter(function(){
              $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
        $('button').each(function(){
            $(this).css('cursor','pointer')
            $(this).css({
                border: 'none'
            })
            if($(this).text()==pagAtual){
                $(this).css({
                    border: 'solid #767e7e'
                });
            }
        })
        $('button').focus(function(){
            pagAtual=$(this).text();
            $('button').each(function(){
                $(this).css({
                    border: 'none'
                })
                if($(this).text()==pagAtual){
                    $(this).css({
                        border: 'solid #767e7e'
                    });
                }
            })
            var tags;
            $('input:checked').each(function(){
                if(!tags){
                    tags = $(this).attr('name');
                }else{
                    tags += ','+$(this).attr('name');
                }
            })
            link='../web/index.php?pagina=cliente&act=list&seleciona=1&pagAtual='+pagAtual+'&tags='+tags+'';          
            $('.tudo').hide()
            $('.tituloProd').text('Aguarde...')
            $(location).attr('href',link)
        })
        
        $('.tituloProd').text('Páginas ');
        //$('.total').text()
        $('.total').text('Registros '+contador+' de '+total+'')
        //alert($('.listaCliente .tudo').attr('contador'));
    })
</script>
<style>
    body {
        -webkit-touch-callout: none;
        -webkit-user-select: none;
        -khtml-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }
    .head{
        text-align: center;
        font-size: 30px;
        padding-top: 10px;
        margin-left: 160px;
    }
    .pag{
        font-size: 15px;
    }
    .total{
        float: right;
        margin-right: 30px;
    }
    table{
        width: 100%;
        border: 1px solid #ccc;
    }
    table td{
        padding: 3px 10px;
    }
    table td div{
        width: 250px;
        word-wrap:  break-word;
    }
    table tr{
        background: rgba(216, 0, 0,0.1);
    }
    .rs{
        width: 600px;
    }
    .ct{
        align-content: center;
    }
    table th{
        background: black;
        color: white;
        font-size: 20px;
        padding: 2px;
    }
    .edicao{
        background-color: white;
        padding: 0;
    }
    td img:hover{
        cursor: pointer;
    }
    .procura{
        float: right;
        margin: 10px;
    }
    .procura img{
        margin-top: 2px;
    }
    .procura2{
        float: right;
        margin: 10px;
    }
    #menu{
        width: 1030px;
    }
    .tituloProd{
        font-size: 20px;
    }
    button{
        box-shadow: 2px 2px 2px gray;
        background-color: #cbcbcb;
        padding: 1px 3px;
        border-radius: 5px;
        text-shadow: 2px 2px 2px white;
        font-weight: bolder;
    }
    .filtroRag{
        padding: 20px;
    }
    .filtroRag span{
        margin-top: 30px;
    }
</style>
<div id="menu">
    <?php if($act!='cad' && $seleciona!=1):?>
        <div class="procura"><input autofocus type="text" name="procura" title="Pesquisar por clientes" /> <img height="18px" src="../web/img/lupa.png" title="Pesquisar por clientes" /></div>
</div>
    <?php else: ?>
        <div class="procura2"><input autofocus type="text" name="procura" title="Pesquisar por clientes" /> <img height="18px" src="../web/img/lupa.png" title="Pesquisar por clientes" /></div>
    <?php endif; ?>
<div class="conteudo">
<?php if($act=='cad'): ?>
<h1>Cadastro de Clientes</h1>
<form method="post" action="../paginas/add.php?act=cad&pagina=cliente" />
<?php
    $variaveis=array('codigo_cliente_integracao','razao_social','nome_fantasia','cnpj_cpf','telefone1_ddd','telefone1_numero','email','contato','endereco','endereco_numero','bairro','complemento','estado','cidade','cep','telefone2_ddd','telefone2_numero','fax_ddd','fax_numero','homepage','inscricao_estadual','inscricao_municipal','inscricao_suframa','produtor_rural','contribuinte','observacao','recomendacao_atraso');
?>
<table>
    <?php for($x=0;$x<count($variaveis);$x++): ?>
    <tr>
        <td align="right"><?= $variaveis[$x] ?></td><td><input name="<?= $variaveis[$x] ?>" type="text" size="55" ></td>
    </tr>
    <?php endfor ?>
</table>
<div class="botao">
    <input type="reset" value="Limpa"/>
    <input type="submit" value="Confirma"/>
</div>
<div id="painel"></div>
</form>
<?php elseif($act=='cons'):
    @$codigo=$_GET['codigo'];
    @$omie=$_GET['omie'];
    if(!$codigo)$codigo='';
    if(!$omie)$omie=0;
    $clientes_cadastro_chave=array("codigo_cliente_omie"=>$omie,
"codigo_cliente_integracao"=>$codigo);
    $dados=$cliente->ConsultarCliente($clientes_cadastro_chave);
?>
<table>
    <tr><th colspan="2">Dados do Cliente</th></tr>
    <?php foreach($dados as $key => $item): ?>
    <tr><td><?= $key ?></td>
        <td>
            <?php
                if($key=='tags'){
                    for($x=0;$x<count($item);$x++){
                        if($x<count($item)-1){
                            echo $item[$x]->tag.',';
                        }else{
                            echo $item[$x]->tag;
                        }
                    }
                }elseif($key!='info'){
                    echo $item;
                }
            ?>
        </td></tr>
    <?php endforeach; ?>
</table>

<?php elseif($act=='alt'): 
    @$codigo=$_GET['codigo'];
    @$omie=$_GET['omie'];
    if(!$codigo)$codigo='';
    if(!$omie)$omie=0;
    $clientes_cadastro_chave=array("codigo_cliente_omie"=>$omie,
"codigo_cliente_integracao"=>$codigo);
    $dados=$cliente->ConsultarCliente($clientes_cadastro_chave); 
?>
<form method="POST" action="../paginas/add.php?act=alt&pagina=cliente" name="alt">
<table>
    <tr><th colspan="2">Dados do Cliente</th></tr>
    <?php $tag=null; ?>
    <?php foreach($dados as $key => $item): ?>
    <tr><td><?= $key ?></td>
        <td>
            <?php
                if($key=='codigo_cliente_omie'||$key=='codigo_cliente_integracao'||$key=='codigo_pais'||$key=='pessoa_fisica'||$key=='exterior'||$key=='optante_simples_nacional'){
                    echo '<input type=hidden name='.$key.' value="'.$item.'" >';
                    echo $item;
                }elseif($key=='tags'){
                    $x=0;
                    foreach($item as $y){
                        if($x<count($item)-1){
                            $tag .= $y->tag.',';
                        }else{
                            $tag .= $y->tag;
                        }
                        $x++;
                    }
                    echo '<input type=text size=55 name=tags value="'.$tag.'" >';
                }elseif($key!='info'){
                    echo '<input type=text size=55px name='.$key.' value="'.$item.'" >';
                }
            ?>
        </td></tr>
    <?php endforeach; ?>
</table>
<input type="submit" value="Salvar" /> 
</form>
<?php elseif($act=='list'): ?>
<script>var pagAtual='<?= $pagAtual ?>'</script>
<span class=tituloProd>Páginas </span>
<?php
    for($g=1;$g <= $dados->total_de_paginas;$g++){
            echo '<button class=paginacao>'.$g.'</button>&nbsp&nbsp';
    }
    foreach($tagLista as $item){
        if($tagsArray){
            if(in_array($item, $tagsArray)){
                $checked='checked';
            }else{
                $checked=null;
            }
        }else{
            $checked=null;
        }
        echo '<span class=filtroRag><input type=checkbox name="'.$item.'" '.$checked.' />'.$item.'</span>';
    }
    if(!$tagsArray){
        $tagsArray=$tagLista;
    }
?>
<div class="head"><?php if($seleciona!=1){
        echo 'Lista de Clientes Cadastrados';
    }else{ 
        echo 'Slecione Um Cliente Abaixo';
    }; ?> <span class="pag">(pág.<?= $dados->pagina ?>/<?= $dados->total_de_paginas ?>)</span>
</div>
<?php 
    /*echo '<pre>';
    $tagLista=array();
    foreach($dados->clientes_cadastro as $item){
        foreach($item->tags as $item){
            $tag=$item->tag;
            //print_r($tag);
        }
    }*/
    //die; 
?>
<div class="total"><script> var total='<?= $dados->total_de_registros ?>'</script></div>
<table class="listaCliente">
    <tr><th>Razão Social/Nome</th><th>CNPJ/CPF</th><!--<th>Contato</th><th>E-mail</th>--></tr>
<?php 
    $contador=0;
    foreach($dados->clientes_cadastro as $cliente): 
        foreach($cliente->tags as $tipo):
                if(in_array($tipo->tag, $tagsArray)): $contador++;?>
                    <tr class="razaosocial tudo" linha="<?= $cliente->codigo_cliente_omie ?>" razao='<?= $cliente->razao_social ?>' cnpj_cpf='<?= $cliente->cnpj_cpf ?>' email="<?= $cliente->email ?>"><td class="rs"><?= mb_strtoupper($cliente->razao_social,'utf-8').'<!--<br><font size=1px>('.$cliente->codigo_cliente_integracao.')</font>-->' ?></td><td align=center ><?= $cliente->cnpj_cpf ?></td><!--<td align=center ><div><?php echo @$cliente->email ?></div></td>--><?php if(@$seleciona!=1):?><td class="edicao"><img title="Altera" height="12px" src="../web/img/editar.png" codigo="<?= $cliente->codigo_cliente_omie ?>" />-<img title="Exclui" height="12px" src="../web/img/excluir.png" codigo="<?= $cliente->codigo_cliente_omie ?>" razao="<?= mb_strtoupper($cliente->razao_social,'utf-8') ?>" /></td><?php endif ?></tr>
    <?php endif; 
        endforeach; 
    endforeach;
?>
</table>
<script>var contador='<?= $contador ?>'</script>
<?php elseif($act=='excl'): ?>


<?php elseif($act=='atualiza'): ?>
<form method="POST" action="../paginas/add.php?act=alt&pagina=cliente" name="alt">
<?php foreach($dados->clientes_cadastro as $item):
        foreach($item as $key => $item2):
            if($key=='info'):
                foreach($item2 as $key2 => $item3):
        ?>
                    <br>----> info -> <?= $key2 ?> -> <?= $item3 ?>
                <?php endforeach; ?>
                <br><br>
            <?php elseif($key=='tags'):
                foreach($item2 as $item4): ?>
                    <br>----> tags -> <?= $item4->tag ?>
                <?php endforeach; ?>
                <br><br>
            <?php else: ?>
                <input name="<?= $key ?>" type="text" value="<?= $item2 ?>" /><br>
            <?php endif;
            echo '<input type="submit" value="Salvar" />';
        endforeach; die;
    endforeach; ?>
<input type="submit" value="Salvar" /> 
</form>               
<?php endif; ?>
</div>