<script>
    $(document).ready(function(){
        tipoBusca="<?= $tipoBusca ?>";
        $('#saldo').css({
            float:'right',
            position: 'relative',
            top: '-50px'
        })
        $('.botao').css({
            float: 'right',
            marginRight: '20px'
        })
        $('.botao input').css({
            borderRadius: '0 0 5px 5px',
            fontWeight: '600',
            backgroundColor: '#63a9c1',
            color: '#111f46',
            padding: '1px 4px'
        })
        $('form').css({
            width: '710px'
        })
        $('table tr:odd').css({
            background: '#ccc'
        })
        $('td img').click(function(){
            if($(this).attr('title')=='Exclui'){
                var razao=$(this).attr('razao');
                var confirma=confirm('Confirma Exclusão de "'+razao+'"');
                if(confirma){
                    var codigo=$(this).attr('codigo');
                    $(location).attr('href','index.php?pagina=cliente&act=excl&codigo='+codigo+'')
                }
            }else if($(this).attr('title')=='Altera'){
                var codigo=$(this).attr('codigo');
                $(location).attr('href','index.php?pagina=cliente&act=alt&omie='+codigo+'')
            }
        })
        $('.procura img').mouseover(function(){
            $(this).css('cursor','pointer')
        })
        
        /// conferir este campo ///
        $('.procura').keyup(function(e){
              var code = e.which;
              if(code==13)e.preventDefault();
              if(code==13||e.keyCode==13){
                  var codigo=$('.procura :input').val();
                  if(codigo){
                    $(location).attr('href','index.php?pagina=cliente&act=cons&codigo='+codigo+'')
                  }
              } 
        })
        $('.procura img').click(function(){
            var codigo=$('.procura :input').val();
              if(codigo){
                $(location).attr('href','index.php?pagina=cliente&act=cons&codigo='+codigo+'')
              }
        })
        //// conferir este campo acima ////
        
        if(seleciona!=1){
            $('.razaosocial').mouseover(function(){
                $(this).css('cursor','pointer')
                $(this).attr('title','dê um duplo clique para ver detalhes.')
            })
            $('.razaosocial').dblclick(function(){
                var codigo=$(this).attr('linha');
                $(location).attr('href','index.php?pagina=cliente&act=cons&omie='+codigo+'')
            })
        }else{
            $('.razaosocial').css({
               background: 'white'
            })
            $('.razaosocial td').css({
                borderBottom: '1px solid #ccc'
            })
            $('.razaosocial').mouseover(function(){
                $(this).css('cursor','pointer')
                $(this).css('background','silver')
                $(this).mouseleave(function(){
                    $('.razaosocial').css('background','white')
                })
                $(this).click(function(){
                    var codigo_cliente=$(this).attr('linha');
                    var razao=$(this).attr('razao');
                    var cnpj_cpf=$(this).attr('cnpj_cpf');
                    var contato=$(this).attr('contato');
                    var email=$(this).attr('email');
                    var endereco=$(this).attr('endereco');
                    var numero=$(this).attr('numero');
                    var bairro=$(this).attr('bairro');
                    var cep=$(this).attr('cep');
                    var cidade=$(this).attr('cidade');
                    $(location).attr('href','../web/index.php?pagina=pedido&act=cad&codigo_cliente='+codigo_cliente+'&razao='+razao+'&cnpj_cpf='+cnpj_cpf+'&contato='+contato+'&email='+email+'&endereco='+endereco+'&endereco_numero='+numero+'&bairro='+bairro+'&cep='+cep+'&cidade='+cidade+'&origem=cliente')
                })
            })
        }      
        $(':submit').click(function(){
            var arr=new Array();
            $(':input').each(function(){
                arr.push($(this).attr('name'));          
            })
        })
        if(act=='adm'){
            $('.vaivem').append($('<img title="Alternar para Cliente" src="../web/img/vaivem.png" height=20px />'))
            $('.vaivem img').click(function(){
                $(location).attr('href','index.php?pagina=produto&act=adm')
            })
            if(funcao=='administrador'){
                $('.mGeral').text('ATUALIZAR TABELA').css({
                    cursor:'pointer'
                }).bind('mouseover',function(){
                    $(this).css({
                        background: '#4e9bae',
                        color: 'white',
                        height: '18px'
                    }).mouseleave(function(){
                        $(this).css({
                           background:'none',
                           color: 'black'
                       })
                    })
                })
            }
            $('.conteudo').css({
                height: '610px',
                width: '1050px',
                background: 'none',
                boxShadow: 'none'
            })
        }
        $('.pagina').text('CLIENTE')
        $(".procura2 input").on("keyup", function(){
            var value = $(this).val().toLowerCase();
            if($('.tipoBusca :checked').val() != 'local'){
                $(".listaCliente .tudo").filter(function(){
                  $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            }
        });
        $('button').each(function(){
            $(this).css('cursor','pointer')
            $(this).css({
                border: 'none'
            })
            if($(this).text()==pagAtual){
                $(this).css({
                    border: 'solid #767e7e'
                });
            }
        })
        $('button').focus(function(){
            pagAtual=$(this).text();
            $('button').each(function(){
                $(this).css({
                    border: 'none'
                })
                if($(this).text()==pagAtual){
                    $(this).css({
                        border: 'solid #767e7e'
                    });
                }
            })
            var tags;
            var tipoBusca;
            $('input:checked').each(function(){
                if(!tags){
                    tags = $(this).attr('name');
                }else{
                    tags += ','+$(this).attr('name');
                }
                tipoBusca=$(':checked[name=tipoBusca]').val();
            })
            link='../web/index.php?pagina=cliente&act=list&seleciona=1&pagAtual='+pagAtual+'&tags='+tags+'&tipoBusca='+tipoBusca+'';         
            $('.tudo').hide()
            $('.tituloProd').text('Aguarde...')
            $(location).attr('href',link)
        })
        
        $('.tituloProd').text('Páginas ');
        $('.total').text('Registros '+contador+' de '+total+'')
        
        $('.recarrega').css('cursor','pointer')
        $('.recarrega').click(function(){
            var tags;
            $('input:checked').each(function(){
                if(!tags){
                    tags = $(this).attr('name');
                }else{
                    tags += ','+$(this).attr('name');
                }
                tipoBusca=$(':checked[name=tipoBusca]').val();
            })
            link='../web/index.php?pagina=cliente&act=list&seleciona=1&pagAtual='+pagAtual+'&tags='+tags+'&tipoBusca='+tipoBusca+'';
            $('.tudo').hide()
            $('.tituloProd').text('Aguarde...')
            $(location).attr('href',link)     
        })
        $('.procura2 img').click(function(){
            if($(':checked[name=tipoBusca]').val()=='local'){
                if($('.procura2 input').val()){
                    var tipoBusca;
                    var tags=null;
                    $('input:checked').each(function(){
                        tipoBusca=$(':checked[name=tipoBusca]').val();
                    })
                    var buscaPor=$('.procura2 input').val();
                    link='../web/index.php?pagina=cliente&act=list&seleciona=1&pagAtual='+pagAtual+'&tags='+tags+'&tipoBusca='+tipoBusca+'&buscaPor='+buscaPor+'';
                    $('.tituloProd').text('Aguarde...')
                    $(location).attr('href',link)                        
                }else{
                    var tags;
                    var tipoBusca;
                    $('input:checked').each(function(){
                        if(!tags){
                            tags = $(this).attr('name');
                        }else{
                            tags += ','+$(this).attr('name');
                        }
                        tipoBusca=$(':checked[name=tipoBusca]').val();
                    })
                    var buscaPor=$('.procura2 input').val();
                    link='../web/index.php?pagina=cliente&act=list&seleciona=1&pagAtual='+pagAtual+'&tags='+tags+'&tipoBusca='+tipoBusca+'&buscaPor='+buscaPor+'';
                    $('.tituloProd').text('Aguarde...')
                    $(location).attr('href',link)
                }
            }else if($('.procura2 input').val()){
                alert('Este tipo de pesquisa só em modo LOCAL.');
                $('.procura2 input[name=procura]').val('').focus();
                $('.listaCliente .tudo').hide()
            }else{
                var tags;
                var tipoBusca;
                $('input:checked').each(function(){
                    if(!tags){
                        tags = $(this).attr('name');
                    }else{
                        tags += ','+$(this).attr('name');
                    }
                    tipoBusca=$(':checked[name=tipoBusca]').val();
                })
                var buscaPor=$('.procura2 input').val();
                link='../web/index.php?pagina=cliente&act=list&seleciona=1&pagAtual='+pagAtual+'&tags='+tags+'&tipoBusca='+tipoBusca+'&buscaPor='+buscaPor+'';
                $('.tituloProd').text('Aguarde...')
                $(location).attr('href',link)
            }
        })
        $(document).keydown(function(e){
            if(e.keyCode==13){
                if($(':checked[name=tipoBusca]').val()=='local'){
                    if($('.procura2 input').val()){
                        var tipoBusca;
                        var tags=null;
                        $('input:checked').each(function(){
                            tipoBusca=$(':checked[name=tipoBusca]').val();
                        })
                        var buscaPor=$('.procura2 input').val();
                        link='../web/index.php?pagina=cliente&act=list&seleciona=1&pagAtual='+pagAtual+'&tags='+tags+'&tipoBusca='+tipoBusca+'&buscaPor='+buscaPor+'';
                        $('.tituloProd').text('Aguarde...')
                        $(location).attr('href',link)                        
                    }else{
                        var tags;
                        var tipoBusca;
                        $('input:checked').each(function(){
                            if(!tags){
                                tags = $(this).attr('name');
                            }else{
                                tags += ','+$(this).attr('name');
                            }
                            tipoBusca=$(':checked[name=tipoBusca]').val();
                        })
                        var buscaPor=$('.procura2 input').val();
                        link='../web/index.php?pagina=cliente&act=list&seleciona=1&pagAtual='+pagAtual+'&tags='+tags+'&tipoBusca='+tipoBusca+'&buscaPor='+buscaPor+'';
                        $('.tituloProd').text('Aguarde...')
                        $(location).attr('href',link)
                    }
                }else if($('.procura2 input').val()){
                    alert('Este tipo de pesquisa só em modo LOCAL.');
                    $('.procura2 input[name=procura]').val('').focus();
                    $('.listaCliente .tudo').hide()
                }else{
                    var tags;
                    var tipoBusca;
                    $('input:checked').each(function(){
                        if(!tags){
                            tags = $(this).attr('name');
                        }else{
                            tags += ','+$(this).attr('name');
                        }
                        tipoBusca=$(':checked[name=tipoBusca]').val();
                    })
                    var buscaPor=$('.procura2 input').val();
                    link='../web/index.php?pagina=cliente&act=list&seleciona=1&pagAtual='+pagAtual+'&tags='+tags+'&tipoBusca='+tipoBusca+'&buscaPor='+buscaPor+'';
                    $('.tituloProd').text('Aguarde...')
                    $(location).attr('href',link)
                }
            }
        })
        $('.tipoBusca input').click(function(){
            var tags;
            tipoBusca=$(this).val();
            $('input:checked').each(function(){
                if(!tags){
                    tags = $(this).attr('name');
                }else{
                    tags += ','+$(this).attr('name');
                }
                tipoBusca=$(':checked[name=tipoBusca]').val();
            })
            
            if(tipoBusca=='local'){
                $('.tudo, .paginacao').hide()                
            }else if(tipoBusca=='servidor'){
                pagAtual='';
                link='../web/index.php?pagina=cliente&act=list&seleciona=1&pagAtual='+pagAtual+'&tags='+tags+'&tipoBusca='+tipoBusca+'';
                $('.tudo').hide()
                $('.tituloProd').text('Aguarde...')
                $(location).attr('href',link)
            }
        })
    })
</script>
<style>
    body {
        -webkit-touch-callout: none;
        -webkit-user-select: none;
        -khtml-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }
    .head{
        text-align: center;
        font-size: 30px;
        padding-top: 10px;
        margin-left: 160px;
    }
    .pag{
        font-size: 15px;
    }
    .total{
        float: right;
        margin-right: 30px;
    }
    table{
        width: 100%;
        border: 1px solid #ccc;
    }
    table td{
        padding: 3px 10px;
    }
    table td div{
        width: 250px;
        word-wrap:  break-word;
    }
    table tr{
        background: rgba(216, 0, 0,0.1);
    }
    .ct{
        align-content: center;
    }
    table th{
        background: green;
        color: white;
        font-size: 20px;
        padding: 2px;
    }
    .edicao{
        background-color: white;
        padding: 0;
    }
    td img:hover{
        cursor: pointer;
    }
    .procura{
        float: right;
        margin: 10px;
    }
    .procura img{
        margin-top: 2px;
    }
    .procura2{
        float: right;
        margin: 10px;
    }
    .procura2 .tipoBusca{
        margin-top: 5px;
        padding: 0 20px;
    }
    #menu{
        width: 1030px;
    }
    .tituloProd{
        font-size: 20px;
    }
    button{
        box-shadow: 2px 2px 2px gray;
        background-color: #cbcbcb;
        padding: 1px 3px;
        border-radius: 5px;
        text-shadow: 2px 2px 2px white;
        font-weight: bolder;
    }
    .filtroRag{
        padding: 20px;
    }
    .filtroRag span{
        margin-top: 30px;
    }
    .recarrega{
        float:left;
        padding: 5px;
    }
</style>
<div id="menu">
    <?php if($act!='cad' && $seleciona!=1 && $act != 'atualiza' && $act!='adm'):?>
        <div class="procura"><input autofocus type="text" name="procura" title="Pesquisar por clientes" /> <img height="18" src="../web/img/lupa.png" title="Pesquisar por clientes" /></div>
</div>
    <?php elseif($act != 'adm' && $act != 'atualiza'):
        switch($tipoBusca){
            case 'servidor':
                $servidor='checked';
                $local=null;
                break;
            case 'local':
                $local='checked';
                $servidor=null;
                break;
            default :
                $servidor='checked';
                $local=null;
                break;
        }
    ?>
<div class="procura2"><input autofocus type="text" name="procura" title="Pesquisar por clientes" /> <img height="18" src="../web/img/lupa.png" title="Pesquisar por clientes" /><br>
    <div class="tipoBusca"><input title="Tipo de busca" type="radio" name="tipoBusca" value="local" <?= $local ?>/>Local &nbsp&nbsp&nbsp<input title="Tipo de busca" type="radio" name="tipoBusca" value="servidor" <?= $servidor ?>/>Servidor</div>
        </div>
    <?php endif; ?>
<div class="conteudo">
<?php if($act=='cad'): ?>
<h1>Cadastro de Clientes</h1>
<form method="post" action="../paginas/add.php?act=cad&pagina=cliente" />
<?php
    $variaveis=array('codigo_cliente_integracao','razao_social','nome_fantasia','cnpj_cpf','telefone1_ddd','telefone1_numero','email','contato','endereco','endereco_numero','bairro','complemento','estado','cidade','cep','telefone2_ddd','telefone2_numero','fax_ddd','fax_numero','homepage','inscricao_estadual','inscricao_municipal','inscricao_suframa','produtor_rural','contribuinte','observacao','recomendacao_atraso');
?>
<table>
    <?php for($x=0;$x<count($variaveis);$x++): ?>
    <tr>
        <td align="right"><?= $variaveis[$x] ?></td><td><input name="<?= $variaveis[$x] ?>" type="text" size="55" ></td>
    </tr>
    <?php endfor ?>
</table>
<div class="botao">
    <input type="reset" value="Limpa"/>
    <input type="submit" value="Confirma"/>
</div>
<div id="painel"></div>
</form>
<?php elseif($act=='cons'):
    @$codigo=$_GET['codigo'];
    @$omie=$_GET['omie'];
    if(!$codigo)$codigo='';
    if(!$omie)$omie=0;
    $clientes_cadastro_chave=array("codigo_cliente_omie"=>$omie,
"codigo_cliente_integracao"=>$codigo);
    $dados=$cliente->ConsultarCliente($clientes_cadastro_chave);
?>
<table>
    <tr><th colspan="2">Dados do Cliente</th></tr>
    <?php foreach($dados as $key => $item): ?>
    <tr><td><?= $key ?></td>
        <td>
            <?php
                if($key=='tags'){
                    for($x=0;$x<count($item);$x++){
                        if($x<count($item)-1){
                            echo $item[$x]->tag.',';
                        }else{
                            echo $item[$x]->tag;
                        }
                    }
                }elseif($key!='info'){
                    echo $item;
                }
            ?>
        </td></tr>
    <?php endforeach; ?>
</table>

<?php elseif($act=='alt'): 
    @$codigo=$_GET['codigo'];
    @$omie=$_GET['omie'];
    if(!$codigo)$codigo='';
    if(!$omie)$omie=0;
    $clientes_cadastro_chave=array("codigo_cliente_omie"=>$omie,
"codigo_cliente_integracao"=>$codigo);
    $dados=$cliente->ConsultarCliente($clientes_cadastro_chave); 
?>
<form method="POST" action="../paginas/add.php?act=alt&pagina=cliente" name="alt">
<table>
    <tr><th colspan="2">Dados do Cliente</th></tr>
    <?php $tag=null; ?>
    <?php foreach($dados as $key => $item): ?>
    <tr><td><?= $key ?></td>
        <td>
            <?php
                if($key=='codigo_cliente_omie'||$key=='codigo_cliente_integracao'||$key=='codigo_pais'||$key=='pessoa_fisica'||$key=='exterior'||$key=='optante_simples_nacional'){
                    echo '<input type=hidden name='.$key.' value="'.$item.'" >';
                    echo $item;
                }elseif($key=='tags'){
                    $x=0;
                    foreach($item as $y){
                        if($x<count($item)-1){
                            $tag .= $y->tag.',';
                        }else{
                            $tag .= $y->tag;
                        }
                        $x++;
                    }
                    echo '<input type=text size=55 name=tags value="'.$tag.'" >';
                }elseif($key!='info'){
                    echo '<input type=text size=55px name='.$key.' value="'.$item.'" >';
                }
            ?>
        </td></tr>
    <?php endforeach; ?>
</table>
<input type="submit" value="Salvar" /> 
</form>
<?php elseif($act=='list'): ?>
<div class=recarrega><img src="../web/img/atualiza.png" height="18" title="Recarregar esta página."/></div>
<span class=tituloProd>Páginas </span>
<?php
    if($tipoBusca=='servidor' || !$tipoBusca){
        for($g=1;$g <= $dados->total_de_paginas;$g++){
                echo '<button class=paginacao>'.$g.'</button>&nbsp&nbsp';
        }
    }
    foreach($tagLista as $item){
        if($tagsArray){
            if(in_array($item, $tagsArray)){
                $checked='checked';
            }else{
                $checked=null;
            }
        }else{
            $checked=null;
        }
        echo '<span class=filtroRag><input type=checkbox name="'.$item.'" '.$checked.' />'.$item.'</span>';
    }
    if(!@$tagsArray[1]){
        $tagsArray=$tagLista;
    }
?>
<div class="head">
<?php 
    if($seleciona!=1){
        echo 'Lista de Clientes Cadastrados';
    }else{ 
        echo 'Slecione Um Cliente Abaixo';
    } 
    if($tipoBusca=='local'){
        $paginaAtual=1;
        $totalPagina=1;
        $totalRegistro=$dao->totalLinhas($search);
    }
?> 
    <span class="pag">(pág.<?= $paginaAtual ?>/<?= $totalPagina ?>)</span>
    <script>var pagAtual='<?= $paginaAtual ?>'</script>
</div>
<div class="total"><script> var total='<?= $totalRegistro; ?>'</script></div>
<table class="listaCliente">
    <tr><th>Razao Social/Nome</th><th>Nome Fantasia/Apelido</th><th>CNPJ/CPF</th></tr>
<?php 
    $contador=0;
    if($tipoBusca=='servidor' || !$tipoBusca){
        foreach($dados_ as $cliente): 
            foreach($cliente->tags as $tipo):
                    if(in_array($tipo->tag, $tagsArray)): $contador++;?>
                        <tr class="razaosocial tudo" linha="<?= $cliente->codigo_cliente_omie ?>" razao="<?= $cliente->nome_fantasia ?>" cnpj_cpf="<?= $cliente->cnpj_cpf ?>" email="<?= $cliente->email ?>" endereco="<?= $cliente->endereco ?>" numero="<?= $cliente->endereco_numero ?>" bairro="<?= $cliente->bairro ?>" cep="<?= $cliente->cep ?>" cidade="<?= $cliente->cidade ?>"><td class="rs"><?= mb_strtoupper($cliente->razao_social,'utf-8') ?></td><td class="nf"><?= mb_strtoupper($cliente->nome_fantasia,'utf-8') ?></td><td align=center ><?= $cliente->cnpj_cpf ?></td><!--<td align=center ><div><?php echo @$cliente->email ?></div></td>--><?php if(@$seleciona!=1):?><td class="edicao"><img title="Altera" height="12" src="../web/img/editar.png" codigo="<?= $cliente->codigo_cliente_omie ?>" />-<img title="Exclui" height="12px" src="../web/img/excluir.png" codigo="<?= $cliente->codigo_cliente_omie ?>" razao="<?= mb_strtoupper($cliente->nome_fantasia,'utf-8') ?>" /></td><?php endif ?></tr>
        <?php endif; 
            endforeach; 
        endforeach;
    }elseif($tipoBusca == 'local'){
        foreach($dados_ as $cliente): $contador++;?>
        <tr class="razaosocial tudo" linha="<?= $cliente->getcodigo_cliente_omie() ?>" razao="<?= $cliente->getnome_fantasia() ?>" cnpj_cpf="<?= $cliente->getcnpj_cpf() ?>" email="<?= $cliente->getemail() ?>" endereco="<?= $cliente->getendereco() ?>" numero="<?= $cliente->getendereco_numero() ?>" bairro="<?= $cliente->getbairro() ?>" cep="<?= $cliente->getcep() ?>" cidade="<?= $cliente->getcidade() ?>">
            <td class="rs"><?= mb_strtoupper($cliente->getrazao_social(),'utf-8') ?></td><td class="nf"><?= mb_strtoupper($cliente->getnome_fantasia(),'utf-8') ?></td><td align=center ><?= $cliente->getcnpj_cpf() ?></td>          </tr>
        <?php endforeach; 
    }
        ?>
</table>
<script>var contador='<?= $contador ?>'</script>
<?php elseif($act=='excl'): ?>


<?php elseif($act=='atualiza'): ?>
      
<?php endif; ?>
</div>