<link rel="stylesheet" href="../web/css/cliente.css" />
<script type="text/javascript" src="../web/js/jqueryCliente.js"></script>
<div id="menu">
    <?php if($act!='cad' && $seleciona!=1 && $act != 'atualiza' && $act!='adm'):?>
        <div class="procura"><input autofocus type="text" name="procura" title="Pesquisar por clientes" /> <img height="18" src="../web/img/lupa.png" title="Pesquisar por clientes" /></div>
</div>
    <?php elseif($act != 'adm' && $act != 'atualiza'):
        switch($tipoBusca){
            case 'servidor':
                $servidor='checked';
                $local=null;
                break;
            case 'local':
                $local='checked';
                $servidor=null;
                break;
            default :
                $servidor='checked';
                $local=null;
                break;
        }
    ?>
<div class="procura2"><input autofocus type="text" name="procura" title="Pesquisar por clientes" /> <img height="18" src="../web/img/lupa.png" title="Pesquisar por clientes" /><br>
    <div class="tipoBusca"><input title="Tipo de busca" type="radio" name="tipoBusca" value="local" <?= $local ?>/>Local &nbsp&nbsp&nbsp<input title="Tipo de busca" type="radio" name="tipoBusca" value="servidor" <?= $servidor ?>/>Servidor</div>
        </div>
    <?php endif; ?>
<div class="conteudo">
<?php if($act=='cad'): ?>
<h1>Cadastro de Clientes</h1>
<form method="post" action="../paginas/add.php?act=cad&pagina=cliente" />
<?php
    $variaveis=array('codigo_cliente_integracao','razao_social','nome_fantasia','cnpj_cpf','telefone1_ddd','telefone1_numero','email','contato','endereco','endereco_numero','bairro','complemento','estado','cidade','cep','telefone2_ddd','telefone2_numero','fax_ddd','fax_numero','homepage','inscricao_estadual','inscricao_municipal','inscricao_suframa','produtor_rural','contribuinte','observacao','recomendacao_atraso');
?>
<table>
    <?php for($x=0;$x<count($variaveis);$x++): ?>
    <tr>
        <td align="right"><?= $variaveis[$x] ?></td><td><input name="<?= $variaveis[$x] ?>" type="text" size="55" ></td>
    </tr>
    <?php endfor ?>
</table>
<div class="botao">
    <input type="reset" value="Limpa"/>
    <input type="submit" value="Confirma"/>
</div>
<div id="painel"></div>
</form>
<?php elseif($act=='cons'):
    @$codigo=$_GET['codigo'];
    @$omie=$_GET['omie'];
    if(!$codigo)$codigo='';
    if(!$omie)$omie=0;
    $clientes_cadastro_chave=array("codigo_cliente_omie"=>$omie,
"codigo_cliente_integracao"=>$codigo);
    $dados=$cliente->ConsultarCliente($clientes_cadastro_chave);
?>
<table>
    <tr><th colspan="2">Dados do Cliente</th></tr>
    <?php foreach($dados as $key => $item): ?>
    <tr><td><?= $key ?></td>
        <td>
            <?php
                if($key=='tags'){
                    for($x=0;$x<count($item);$x++){
                        if($x<count($item)-1){
                            echo $item[$x]->tag.',';
                        }else{
                            echo $item[$x]->tag;
                        }
                    }
                }elseif($key!='info'){
                    echo $item;
                }
            ?>
        </td></tr>
    <?php endforeach; ?>
</table>

<?php elseif($act=='alt'): 
    @$codigo=$_GET['codigo'];
    @$omie=$_GET['omie'];
    if(!$codigo)$codigo='';
    if(!$omie)$omie=0;
    $clientes_cadastro_chave=array("codigo_cliente_omie"=>$omie,
"codigo_cliente_integracao"=>$codigo);
    $dados=$cliente->ConsultarCliente($clientes_cadastro_chave); 
?>
<form method="POST" action="../paginas/add.php?act=alt&pagina=cliente" name="alt">
<table>
    <tr><th colspan="2">Dados do Cliente</th></tr>
    <?php $tag=null; ?>
    <?php foreach($dados as $key => $item): ?>
    <tr><td><?= $key ?></td>
        <td>
            <?php
                if($key=='codigo_cliente_omie'||$key=='codigo_cliente_integracao'||$key=='codigo_pais'||$key=='pessoa_fisica'||$key=='exterior'||$key=='optante_simples_nacional'){
                    echo '<input type=hidden name='.$key.' value="'.$item.'" >';
                    echo $item;
                }elseif($key=='tags'){
                    $x=0;
                    foreach($item as $y){
                        if($x<count($item)-1){
                            $tag .= $y->tag.',';
                        }else{
                            $tag .= $y->tag;
                        }
                        $x++;
                    }
                    echo '<input type=text size=55 name=tags value="'.$tag.'" >';
                }elseif($key!='info'){
                    echo '<input type=text size=55px name='.$key.' value="'.$item.'" >';
                }
            ?>
        </td></tr>
    <?php endforeach; ?>
</table>
<input type="submit" value="Salvar" /> 
</form>
<?php elseif($act=='list'): ?>
<div class=recarrega><img src="../web/img/atualiza.png" height="18" title="Recarregar esta página."/></div>
<span class=tituloProd>Páginas </span>
<?php
    if(($tipoBusca=='servidor' || !$tipoBusca) && is_object($dados)){
        for($g=1;$g <= $dados->total_de_paginas;$g++){
                echo '<button class=paginacao>'.$g.'</button>&nbsp&nbsp';
        }
    }
    foreach($tagLista as $item){
        if($tagsArray){
            if(in_array($item, $tagsArray)){
                $checked='checked';
            }else{
                $checked=null;
            }
        }else{
            $checked=null;
        }
        echo '<span class=filtroTag><input type=checkbox name="'.$item.'" '.$checked.' />'.$item.'</span>';
    }
    if(!@$tagsArray[1]){
        $tagsArray=$tagLista;
    }
?>
<div class="head">
<?php 
    if($seleciona!=1){
        echo 'Lista de Clientes Cadastrados';
    }else{ 
        echo 'Slecione Um Cliente Abaixo';
    } 
    if($tipoBusca=='local'){
        $paginaAtual=1;
        $totalPagina=1;
        $totalRegistro=$dao->totalLinhas($search);
    }
?> 
    <span class="pag">(pág.<?= @$paginaAtual ?>/<?= @$totalPagina ?>)</span>
    <script>var pagAtual='<?= @$paginaAtual ?>'</script>
</div>
<div class="total"><script> var total='<?= $totalRegistro; ?>'</script></div>
<table class="listaCliente">
    <tr><th>Razao Social/Nome</th><th>Nome Fantasia/Apelido</th><th>CNPJ/CPF</th></tr>
<?php 
    $contador=0;
    if(($tipoBusca=='servidor' || !$tipoBusca) && $dados):
        foreach($dados_ as $cliente): 
            foreach($cliente->tags as $tipo):
                    if(in_array($tipo->tag, $tagsArray)): $contador++; ?>
                        <tr class="razaosocial tudo" linha="<?= $cliente->codigo_cliente_omie ?>" razao="<?= $cliente->nome_fantasia ?>" cnpj_cpf="<?= $cliente->cnpj_cpf ?>" email="<?= $cliente->email ?>" endereco="<?= $cliente->endereco ?>" numero="<?= $cliente->endereco_numero ?>" bairro="<?= $cliente->bairro ?>" cep="<?= $cliente->cep ?>" cidade="<?= $cliente->cidade ?>" >                                              <td class="rs"><?= mb_strtoupper($cliente->razao_social,'utf-8') ?></td>                            <td class="nf"><?= mb_strtoupper($cliente->nome_fantasia,'utf-8') ?></td>
                            <td align=center ><?= $cliente->cnpj_cpf ?></td>
                                <?php if(@$seleciona!=1): ?>
                                    <td class="edicao"><img title="Altera" height="12" src="../web/img/editar.png" codigo="<?= $cliente->codigo_cliente_omie ?>" />-<img title="Exclui" height="12px" src="../web/img/excluir.png" codigo="<?= $cliente->codigo_cliente_omie ?>" razao="<?= mb_strtoupper($cliente->nome_fantasia,'utf-8') ?>" /></td>
                                <?php endif; ?>
                        </tr>
        <?php endif; 
            endforeach; 
        endforeach;
    elseif($tipoBusca == 'local'):
        foreach($dados_ as $cliente): $contador++;?>
        <tr class="razaosocial tudo" linha="<?= $cliente->getcodigo_cliente_omie() ?>" razao="<?= $cliente->getnome_fantasia() ?>" cnpj_cpf="<?= $cliente->getcnpj_cpf() ?>" email="<?= $cliente->getemail() ?>" endereco="<?= $cliente->getendereco() ?>" numero="<?= $cliente->getendereco_numero() ?>" bairro="<?= $cliente->getbairro() ?>" cep="<?= $cliente->getcep() ?>" cidade="<?= $cliente->getcidade() ?>">
            <td class="rs"><?= mb_strtoupper($cliente->getrazao_social(),'utf-8') ?></td>
            <td class="nf"><?= mb_strtoupper($cliente->getnome_fantasia(),'utf-8') ?></td>
            <td class="cnpj" align=center ><?= $cliente->getcnpj_cpf() ?></td>          
        </tr>
        <?php endforeach; 
    endif;
?>
</table>
<script>var contador='<?= $contador ?>'</script>     
<?php endif; ?>
</div>