<script>
    $(document).ready(function(){
        $('#saldo').css({
            float:'right',
            position: 'relative',
            top: '-50px'
        })
        $('.botao').css({
            float: 'right',
            marginRight: '20px'
        })
        $('.botao input').css({
            borderRadius: '0 0 5px 5px',
            fontWeight: '600',
            backgroundColor: '#63a9c1',
            color: '#111f46',
            padding: '1px 4px'
        })
        $('form').css({
            width: '710px'
        })
        $('table tr:odd').css({
            background: '#ccc'
        })
        $('td img').click(function(){
            if($(this).attr('title')=='Exclui'){
                var razao=$(this).attr('razao');
                var confirma=confirm('Confirma Exclusão de "'+razao+'"');
                if(confirma){
                    var codigo=$(this).attr('codigo');
                    $(location).attr('href','index.php?pagina=produto&act=excl&codigo='+codigo+'')
                }
            }else if($(this).attr('title')=='Altera'){
                var codigo=$(this).attr('codigo');
                $(location).attr('href','index.php?pagina=produto&act=alt&codigo='+codigo+'')
            }
        })
        $('.procura img').mouseover(function(){
            $(this).css('cursor','pointer')
        })
        $('.procura').keyup(function(e){
              var code = e.which; // recommended to use e.which, it's normalized across browsers
              if(code==13)e.preventDefault();
              if(code==13||e.keyCode==13){
                  var codigo=$('.procura :input').val();
                  if(codigo){
                    $(location).attr('href','index.php?pagina=produto&act=cons&codigo='+codigo+'')
                  }
              } 
        })
        $('.procura img').click(function(){
            var codigo=$('.procura :input').val();
              if(codigo){
                $(location).attr('href','index.php?pagina=produto&act=cons&codigo='+codigo+'')
              }
        })
        $('.razaosocial').mouseover(function(){
            $(this).css('cursor','pointer')
            $(this).attr('title','dê um duplo clique para ver detalhes.')
        })
        $('.razaosocial').dblclick(function(){
            var codigo=$(this).attr('linha');
            $(location).attr('href','index.php?pagina=produto&act=cons&codigo='+codigo+'')
        })
        $(':submit').click(function(){
            var arr=new Array();
            $(':input').each(function(){
                arr.push($(this).attr('name'));          
            })
        })
        var pagina=null;
        $('.pagina').text(pag)
        /*if(act=='excl'){
            $(location).attr('href','index.php?pagina=produto&act=list');
        }*/
    })
</script>
<style>
    #menu ul {
        padding:0px;
        margin:0px;
        background-color:#EDEDED;
        list-style:none;
        font-size: 20px;
    }
    #menu ul li{
        display: inline;
    }
    .head{
        text-align: center;
        font-size: 25px;
    }
    .pag{
        font-size: 12px;
    }
    .total{
        float: right;
    }
    table{
        width: 700px;
    }
    table td{
        padding: 3px 10px;
    }
    table tr{
        background: rgba(216, 0, 0,0.1);
    }
    .rs{
        width: 70%;
    }
    .ct{
        align-content: center;
    }
    table th{
        background: black;
        color: white;
        font-size: 20px;
        padding: 2px;
    }
    .edicao{
        background-color: white;
        padding: 0;
    }
    td img:hover{
        cursor: pointer;
    }
    .procura{
        float: right;
        margin: 10px;
    }
    .procura img{
        margin-top: 2px;
    }
</style>
<div id="menu">
    <ul>
        <li><a href=<?= Utils::createLink('pedido',array('act'=>'cad')); ?>>Incluir</a></li>
        <li><a href=<?= Utils::createLink('pedido',array('act'=>'list')); ?>>Listar</a></li>
    </ul>
    <?php if($act!='cad'){?>
    <div class="procura"><input autofocus type="text" name="procura" title="Pesquisar por produtos" /> <img height="18px" src="../web/img/lupa.png" title="Pesquisar por produtos" /></div>
    <?php } ?>
    <script>var pag="PRÉ-VENDA";</script>
</div>
<div class="conteudo">
<?php if($act=='cad'): ?>
<h1>Cadastro de Produtos</h1>
<form method="post" action="../paginas/add.php?act=cad&pagina=produto" />
<?php
    $variaveis=array('codigo_produto_integracao','descricao','unidade','ncm','valor_unitario');
?>
<table>
    <?php for($x=0;$x<count($variaveis);$x++): ?>
    <tr>
        <td align="right"><?= $variaveis[$x] ?></td><td><input name="<?= $variaveis[$x] ?>" type="text" size="55" required></td>
    </tr>
    <?php endfor ?>
</table>
<div class="botao">
    <input type="reset" value="Limpa"/>
    <input type="submit" value="Confirma"/>
</div>
<div id="painel"></div>
</form>
<?php elseif($act=='cons'):
    @$codigo_produto=$_GET['codigo'];
    if(!$codigo_produto)$codigo_produto=0;
    $produto_servico_cadastro_chave=array("codigo_produto"=>$codigo_produto,"codigo_produto_integracao"=>"","codigo"=>"");
    $dados=$produtos->ConsultarProduto($produto_servico_cadastro_chave);
?>
<table>
    <tr><th colspan="2">Detalhes do Produto</th></tr>
    <?php foreach($dados as $key => $item): ?>
    <tr><td><?= $key ?></td>
        <td>
            <?php
                if($key=='dadosIbpt'){
                    foreach($item as $key2 => $item2){
                        if($item2){
                            echo $key2.': '.$item2.'&nbsp&nbsp&nbsp';
                        }
                    }
                }elseif($key=='recomendacoes_fiscais'){
                    foreach($item as $key2 => $item2){
                        if($item2){
                            echo $key2.': '.$item2.'&nbsp&nbsp&nbsp';
                        }
                    }
                }else{
                    echo $item;
                }
            ?>
        </td></tr>
    <?php endforeach; ?>
</table>
<?php elseif($act=='alt'): 
    @$codigo_produto=$_GET['codigo'];
    if(!$codigo_produto)$codigo_produto=0;
    $produto_servico_cadastro_chave=array("codigo_produto"=>$codigo_produto,"codigo_produto_integracao"=>"","codigo"=>"");
    $dados=$produtos->ConsultarProduto($produto_servico_cadastro_chave);
?>
<form method="POST" action="../paginas/add.php?act=alt&pagina=produto" name="alt">
<table>
    <tr><th colspan="2">Detalhe do Produto</th></tr>
    <?php foreach($dados as $key => $item): ?>
    <tr><td><?= $key ?></td>
        <td>
            <?php
                if($key=='codigo_produto'){
                    echo '<input type=hidden name='.$key.' value="'.$item.'" >';
                    echo $item;
                }elseif($key=='dadosIbpt'){
                    foreach($item as $key2 => $item2){
                        if($item2){
                            echo $key2.': <input type=test name=dadosIbpt value="'.$item2.'"&nbsp&nbsp&nbsp';
                        }
                    }
                }elseif($key=='recomendacoes_fiscais'){
                    foreach($item as $key2 => $item2){
                        if($item2){
                            echo $key2.': <input type=test name=dadosIbpt value="'.$item2.'"&nbsp&nbsp&nbsp';
                        }
                    }
                }else{
                    echo '<input type=text size=55px name='.$key.' value="'.$item.'" >';
                }
            ?>
        </td></tr>
    <?php endforeach; ?>
</table>
<input type="submit" value="Salvar" /> 
</form>
<?php elseif($act=='list'): 
    
?>

<div class="head">Lista de Pedidos <span class="pag">(pág.<?= $dados->pagina ?>/<?= $dados->total_de_paginas ?>)</span>
</div>
<div class="total">total de registros <?= $dados->total_de_registros ?></div>
<table>
    <tr><th>Código</th><th>Cód. Int.</th><th>Produto</th><th>Quant. em Estoque/Mínimo</th></tr>
    <?php 
    foreach($dados->produto_servico_cadastro as $produto): ?>
    <tr class="razaosocial" linha="<?= $produto->codigo_produto ?>"><td><?= $produto->codigo_produto ?></td><td><?= $produto->codigo_produto_integracao ?></td><td class="rs"><?= mb_strtoupper($produto->descricao,'utf-8') ?></td><td align=center ><?php if($produto->quantidade_estoque < $produto->estoque_minimo){echo '<font color=red>'.$produto->quantidade_estoque.'</font>/'.$produto->estoque_minimo;}else{echo $produto->quantidade_estoque.'/'.$produto->estoque_minimo;} ?></td><td class="edicao"><img title="Altera" height="12px" src="../web/img/editar.png" codigo="<?= $produto->codigo_produto ?>" />-<img title="Exclui" height="12px" src="../web/img/excluir.png" codigo="<?= $produto->codigo_produto ?>" razao="<?= mb_strtoupper($produto->descricao,'utf-8') ?>" /></td></tr>
    <?php endforeach; ?>
</table>
<?php else: 
    $pvpListarRequest=array("pagina"=>1,"registros_por_pagina"=>50,"apenas_importado_api"=>"N");
    $dados=$pedido->ListarPedidos($pvpListarRequest);
    echo '<pre>';
    //print_r($dados->pedido_venda_produto[4]);
    $posicao=array('Pedido de Venda','Separar Estoque','Faturar','Faturado','Entrega');
    foreach($dados->pedido_venda_produto as $key => $item){
            if($item->cabecalho->etapa=='10'){
                $triagem['Pedido de Venda']=$item->cabecalho;
            }elseif($item->cabecalho->etapa=='20'){
                $triagem['Separar Estoque']=$item->cabecalho;
            }elseif($item->cabecalho->etapa=='50'){
                $triagem['Faturar']=$item->cabecalho;
            }elseif($item->cabecalho->etapa=='60'){
                $triagem['Faturado']=$item->cabecalho;
            }elseif($item->cabecalho->etapa=='70'){
                $triagem['Entrega']=$item->cabecalho;
            }
    }
     $clientes_cadastro_chave=array("codigo_cliente_omie"=>0,"codigo_cliente_integracao"=>"");    
    echo '<ul>';
    $y=1;
    foreach($posicao as $item){
        echo '<ul><li>';
            echo $item;
                echo '<ul>';
                if(@$triagem[$item]->numero_pedido){
                    echo '<li>Pedido Nº'.number_format($triagem[$item]->numero_pedido);
                    switch($y){
                        case 1:
                            echo ' <select name=etapa>';
                                echo '<option value=1></option>';
                                echo '<option value=1>2</option>';
                                echo '<option value=1>3</option>';
                                echo '<option value=1>4</option>';
                                echo '<option value=1>5</option>';
                            echo '</select>';
                            break;
                        case 2:
                            echo ' <select name=etapa>';
                                echo '<option value=2></option>';
                                echo '<option value=2>1</option>';
                                echo '<option value=2>3</option>';
                                echo '<option value=2>4</option>';
                                echo '<option value=2>5</option>';
                            echo '</select>';
                            break;
                        case 3:
                            echo ' <select name=etapa>';
                                echo '<option value=3></option>';
                                echo '<option value=3>1</option>';
                                echo '<option value=3>2</option>';
                                echo '<option value=3>4</option>';
                                echo '<option value=3>5</option>';
                            echo '</select>';
                            break;
                        case 4:
                            echo ' <select name=etapa>';
                                echo '<option value=4></option>';
                                echo '<option value=4>5</option>';
                            echo '</select>';
                            break;
                        case 5:
                            echo ' <select name=etapa>';
                                echo '<option value=5></option>';
                                echo '<option value=5>4</option>';
                            echo '</select>';
                            break;
                    }
                    echo ' Alterar Etapa</li>';
                    $clientes_cadastro_chave=array('codigo_cliente_omie'=>$triagem[$item]->codigo_cliente);
                    $dados_cliente=$cliente->ConsultarCliente($clientes_cadastro_chave);
                    echo '<li><b>'.$dados_cliente->nome_fantasia.'</b></li>';
                    $prev=Utils::datafatura($triagem[$item]->data_previsao,$triagem[$item]->etapa);
                    $cor=substr(strstr($prev,','),1);
                    $fatura=strstr($prev,',',true);
                    //print_r($);
                    echo '<li><font color='.$cor.'>'.$fatura.'</font></li>';
                }
                echo '</ul>';
        echo '</li></ul>';
        $y++;
    }
    echo '</ul>';
?>
<?php endif; ?>
</div>