<script>
    $(document).ready(function(){
        $('#saldo').css({
            float:'right',
            position: 'relative',
            top: '-50px'
        })
        $('.botao').css({
            float: 'right',
            marginRight: '20px'
        })
        $('.botao input').css({
            borderRadius: '0 0 5px 5px',
            fontWeight: '600',
            backgroundColor: '#63a9c1',
            color: '#111f46',
            padding: '1px 4px'
        })
        $('form').css({
            width: '710px',
            //border: 'solid red'
        })
        $('table tr:odd').css({
            background: '#ccc'
        })
        $('td img').click(function(){
            if($(this).attr('title')=='Exclui'){
                var razao=$(this).attr('razao');
                var confirma=confirm('Confirma Exclusão de "'+razao+'"');
                if(confirma){
                    var codigo=$(this).attr('codigo');
                    $(location).attr('href','index.php?pagina=cliente&act=excl&codigo='+codigo+'')
                }
            }else if($(this).attr('title')=='Altera'){
                var codigo=$(this).attr('codigo');
                $(location).attr('href','index.php?pagina=cliente&act=alt&omie='+codigo+'')
            }
        })
        $('.procura img').mouseover(function(){
            $(this).css('cursor','pointer')
        })
        $('.procura').keyup(function(e){
              var code = e.which; // recommended to use e.which, it's normalized across browsers
              if(code==13)e.preventDefault();
              if(code==13||e.keyCode==13){
                  var codigo=$('.procura :input').val();
                  if(codigo){
                    $(location).attr('href','index.php?pagina=cliente&act=cons&codigo='+codigo+'')
                  }
              } 
        })
        $('.procura img').click(function(){
            var codigo=$('.procura :input').val();
              if(codigo){
                $(location).attr('href','index.php?pagina=cliente&act=cons&codigo='+codigo+'')
              }
        })
        $('.razaosocial').mouseover(function(){
            $(this).css('cursor','pointer')
            $(this).attr('title','dê um duplo clique para ver detalhes.')
        })
        $('.razaosocial').dblclick(function(){
            var codigo=$(this).attr('linha');
            $(location).attr('href','index.php?pagina=cliente&act=cons&omie='+codigo+'')
        })
        $(':submit').click(function(){
            var arr=new Array();
            $(':input').each(function(){
                arr.push($(this).attr('name'));          
            })
        })
    })
</script>
<style>
    #menu ul {
        padding:0px;
        margin:0px;
        background-color:#EDEDED;
        list-style:none;
        font-size: 20px;
    }
    #menu ul li{
        display: inline;
    }
    .head{
        text-align: center;
        font-size: 25px;
    }
    .pag{
        font-size: 12px;
    }
    .total{
        float: right;
    }
    table{
        width: 700px;
    }
    table td{
        padding: 3px 10px;
    }
    table tr{
        background: rgba(216, 0, 0,0.1);
    }
    .rs{
        width: 70%;
    }
    .ct{
        align-content: center;
    }
    table th{
        background: black;
        color: white;
        font-size: 20px;
        padding: 2px;
    }
    .edicao{
        background-color: white;
        padding: 0;
    }
    td img:hover{
        cursor: pointer;
    }
    .procura{
        float: right;
        margin: 10px;
    }
    .procura img{
        margin-top: 2px;
    }
</style>
<div id="menu">
    <ul>
        <li><a href=<?= Utils::createLink('produto',array('act'=>'cad')); ?>>Incluir</a></li>
        <li><a href=<?= Utils::createLink('produto',array('act'=>'list')); ?>>Listar</a></li>
    </ul>
    <?php if($act!='cad'){?>
    <div class="procura"><input autofocus type="text" name="procura" title="Pesquisar por produtos" /> <img height="18px" src="../web/img/lupa.png" title="Pesquisar por produtos" /></div>
    <?php } ?>
</div>
<div class="conteudo">
<?php if($act=='cad'): ?>
<h1>Cadastro de Produtos</h1>
<form method="post" action="../paginas/add.php?act=cad" />
<?php
//[tipo_atividade] => [cnae] [tags] => [logradouro] => [importado_api] => [bloqueado] => [cidade_ibge] => ) 
    $variaveis=array('codigo_cliente_integracao','razao_social','nome_fantasia','cnpj_cpf','telefone1_ddd','telefone1_numero','email','contato','endereco','endereco_numero','bairro','complemento','estado','cidade','cep','telefone2_ddd','telefone2_numero','fax_ddd','fax_numero','homepage','inscricao_estadual','inscricao_municipal','inscricao_suframa','produtor_rural','contribuinte','observacao','recomendacao_atraso');
?>
<table>
    <?php for($x=0;$x<count($variaveis);$x++): ?>
    <tr>
        <td align="right"><?= $variaveis[$x] ?></td><td><input name="<?= $variaveis[$x] ?>" type="text" size="55" required></td>
    </tr>
    <?php endfor ?>
</table>
<div class="botao">
    <input type="reset" value="Limpa"/>
    <input type="submit" value="Confirma"/>
</div>
<div id="painel"></div>
</form>
<?php elseif($act=='cons'):
    @$codigo=$_GET['codigo'];
    @$omie=$_GET['omie'];
    if(!$codigo)$codigo='';
    if(!$omie)$omie=0;
    $clientes_cadastro_chave=array("codigo_cliente_omie"=>$omie,
"codigo_cliente_integracao"=>$codigo);
    $dados=$cliente->ConsultarCliente($clientes_cadastro_chave); 
?>
<table>
    <tr><th colspan="2">Dados do Cliente</th></tr>
    <?php foreach($dados as $key => $item): ?>
    <tr><td><?= $key ?></td>
        <td>
            <?php
                if($key=='tags'){
                    for($x=0;$x<count($item);$x++){
                        if($x<count($item)-1){
                            echo $item[$x]->tag.',';
                        }else{
                            echo $item[$x]->tag;
                        }
                    }
                }elseif($key!='info'){
                    echo $item;
                }
            ?>
        </td></tr>
    <?php endforeach; ?>
</table>

<?php elseif($act=='alt'): 
    @$codigo=$_GET['codigo'];
    @$omie=$_GET['omie'];
    if(!$codigo)$codigo='';
    if(!$omie)$omie=0;
    $clientes_cadastro_chave=array("codigo_cliente_omie"=>$omie,
"codigo_cliente_integracao"=>$codigo);
    $dados=$cliente->ConsultarCliente($clientes_cadastro_chave); 
?>
<form method="POST" action="../paginas/add.php?act=alt" name="alt">
<table>
    <tr><th colspan="2">Dados do Cliente</th></tr>
    <?php $tag=null; ?>
    <?php foreach($dados as $key => $item): ?>
    <tr><td><?= $key ?></td>
        <td>
            <?php
                if($key=='codigo_cliente_omie'||$key=='codigo_cliente_integracao'||$key=='codigo_pais'||$key=='pessoa_fisica'||$key=='exterior'||$key=='optante_simples_nacional'){
                    echo '<input type=hidden name='.$key.' value="'.$item.'" >';
                    echo $item;
                }elseif($key=='tags'){
                    $x=0;
                    foreach($item as $y){
                        if($x<count($item)-1){
                            $tag .= $y->tag.',';
                        }else{
                            $tag .= $y->tag;
                        }
                        $x++;
                    }
                    echo '<input type=text size=55 name=tags value="'.$tag.'" >';
                }elseif($key!='info'){
                    echo '<input type=text size=55px name='.$key.' value="'.$item.'" >';
                }
            ?>
        </td></tr>
    <?php endforeach; ?>
</table>
<input type="submit" value="Salvar" /> 
</form>
<?php elseif($act=='list'): 
    $produto_servico_list_request=array("pagina"=>1,"registros_por_pagina"=>50,"apenas_importado_api"=>"N","filtrar_apenas_omiepdv"=>"N");
    $dados=$produtos->ListarProdutos($produto_servico_list_request);
    //echo '<pre>';
    //print_r($dados->produto_servico_cadastro);die;
?>
<div class="head">Lista de Produtos Cadastrados <span class="pag">(pág.<?= $dados->pagina ?>/<?= $dados->total_de_paginas ?>)</span>
</div>
<div class="total">total de registros <?= $dados->total_de_registros ?></div>
<table>
    <tr><th>Produto</th><th>Quant. em Estoque/Mínimo</th></tr>
    <?php 
    foreach($dados->produto_servico_cadastro as $produto): ?>
    <tr class="razaosocial" linha="<?= $produto->codigo_produto_omie ?>"><td class="rs"><?= mb_strtoupper($produto->descricao,'utf-8').'<br><font size=1px>('.$produto->codigo_produto_integracao.')</font>' ?></td><td align=center ><?php if($produto->quantidade_estoque < $produto->estoque_minimo){echo '<font color=red>'.$produto->quantidade_estoque.'</font>/'.$produto->estoque_minimo;}else{echo $produto->quantidade_estoque.'/'.$produto->estoque_minimo;} ?></td><td class="edicao"><img title="Altera" height="12px" src="../web/img/editar.png" codigo="<?= $produto->codigo_produto_omie ?>" />-<img title="Exclui" height="12px" src="../web/img/excluir.png" codigo="<?= $produto->codigo_produto_omie ?>" razao="<?= mb_strtoupper($produto->descricao,'utf-8') ?>" /></td></tr>
    <?php endforeach; ?>
</table>

<?php elseif($act=='excl'): ?>


<?php endif; ?>
</div>
