<script>
    $(document).ready(function(){
        $('#saldo').css({
            float:'right',
            position: 'relative',
            top: '-50px'
        })
        $('.botao').css({
            float: 'right',
            marginRight: '20px'
        })
        $('.botao input').css({
            borderRadius: '0 0 5px 5px',
            fontWeight: '600',
            backgroundColor: '#63a9c1',
            color: '#111f46',
            padding: '1px 4px'
        })
        $('form').css({
            width: '710px'
        })
        $('table tr:odd').css({
            background: '#ccc'
        })
        $('td img').click(function(){
            if($(this).attr('title')=='Exclui'){
                var razao=$(this).attr('razao');
                var confirma=confirm('Confirma Exclusão de "'+razao+'"');
                if(confirma){
                    var codigo=$(this).attr('codigo');
                    $(location).attr('href','index.php?pagina=produto&act=excl&codigo='+codigo+'')
                }
            }else if($(this).attr('title')=='Altera'){
                var codigo=$(this).attr('codigo');
                $(location).attr('href','index.php?pagina=produto&act=alt&codigo='+codigo+'')
            }
        })
        $('.procura img').mouseover(function(){
            $(this).css('cursor','pointer')
        })
        $('.procura').keyup(function(e){
              var code = e.which; // recommended to use e.which, it's normalized across browsers
              if(code==13)e.preventDefault();
              if(code==13||e.keyCode==13){
                  var codigo=$('.procura :input').val();
                  if(codigo){
                    $(location).attr('href','index.php?pagina=produto&act=cons&codigo='+codigo+'')
                  }
              } 
        })
        $('.procura img').click(function(){
            var codigo=$('.procura :input').val();
              if(codigo){
                $(location).attr('href','index.php?pagina=produto&act=cons&codigo='+codigo+'')
              }
        })
        $('.razaosocial').mouseover(function(){
            $(this).css('cursor','pointer')
            $(this).attr('title','dê um duplo clique para ver detalhes.')
        })
        $('.razaosocial').dblclick(function(){
            var codigo=$(this).attr('linha');
            $(location).attr('href','index.php?pagina=produto&act=cons&codigo='+codigo+'')
        })
        $(':submit').click(function(){
            var arr=new Array();
            $(':input').each(function(){
                arr.push($(this).attr('name'));          
            })
        })
        var pagina=null;
        $('.vaivem').append($('<img title="Alternar para Cliente" src="../web/img/vaivem.png" height=20px />'))
        $('.vaivem img').click(function(){
            $(location).attr('href','index.php?pagina=cliente&act=adm&seleciona=1&tags=undefined')
        })
        $('.pagina').text(pag)
        if(funcao=='administrador'){
            $('.mGeral').text('ATUALIZAR TABELA').css({
                cursor:'pointer'
            }).bind('mouseover',function(){
                $(this).css({
                    background: '#4e9bae',
                    color: 'white',
                    height: '18px'
                }).mouseleave(function(){
                    $(this).css({
                       background:'none',
                       color: 'black'
                   })
                })
            })
            $('.mGeral').click(function(){
                //$(location).attr('href','../web/index.php?pagina=cliente&act=atualiza&seleciona=0')
            })
        }
        /*if(act=='excl'){
            $(location).attr('href','index.php?pagina=produto&act=list');
        }*/
    })
</script>
<style>
    #menu ul {
        padding:0px;
        margin:0px;
        background-color:#EDEDED;
        list-style:none;
        font-size: 20px;
    }
    #menu ul li{
        display: inline;
    }
    .head{
        text-align: center;
        font-size: 25px;
    }
    .pag{
        font-size: 12px;
    }
    .total{
        float: right;
    }
    table{
        width: 700px;
        margin: auto;
    }
    table td{
        padding: 3px 10px;
    }
    table tr{
        //background: rgba(216, 0, 0,0.1);
    }
    .rs{
        width: 70%;
    }
    .ct{
        align-content: center;
    }
    table th{
        //background: black;
        //color: white;
        font-size: 20px;
        //padding: 2px;
    }
    .edicao{
        background-color: white;
        padding: 0;
    }
    td img:hover{
        cursor: pointer;
    }
    .procura{
        float: right;
        margin: 10px;
    }
    .procura img{
        margin-top: 2px;
    }
    .conteudo{
        height: 610px;
        width: 1050px;
        background: none;
        box-shadow: none;
        //border: solid red;
    }
</style>
<div id="menu">
    <!--<ul>
        <li><a href=<?= Utils::createLink('produto',array('act'=>'cad')); ?>>Incluir</a></li>
        <li><a href=<?= Utils::createLink('produto',array('act'=>'list')); ?>>Listar</a></li>
    </ul>-->
    <?php if($act!='cad'){?>
    <!--<div class="procura"><input autofocus type="text" name="procura" title="Pesquisar por produtos" /> <img height="18px" src="../web/img/lupa.png" title="Pesquisar por produtos" /></div>-->
    <?php } ?>
    <script>var pag="<?= strtoupper($_GET['pagina']); ?>";</script>
</div>
<div class="conteudo">
<?php if($act=='adm'): ?>
    <table class="atualizacao">
        <tr><th>LOCAL</th><th><th>SERVIDOR</th></tr>
    </table>    
<?php elseif($act=='cad'): ?>
<h1>Cadastro de Produtos</h1>
<form method="post" action="../paginas/add.php?act=cad&pagina=produto" />
<?php
    $variaveis=array('codigo_produto_integracao','descricao','unidade','ncm','valor_unitario');
?>
<table>
    <?php for($x=0;$x<count($variaveis);$x++): ?>
    <tr>
        <td align="right"><?= $variaveis[$x] ?></td><td><input name="<?= $variaveis[$x] ?>" type="text" size="55" required></td>
    </tr>
    <?php endfor ?>
</table>
<div class="botao">
    <input type="reset" value="Limpa"/>
    <input type="submit" value="Confirma"/>
</div>
<div id="painel"></div>
</form>
<?php elseif($act=='cons'): ?>
<table>
    <tr><th colspan="2">Detalhes do Produto</th></tr>
    <?php foreach($dados as $key => $item): ?>
    <tr><td><?= $key ?></td>
        <td>
            <?php
                if($key=='dadosIbpt'){
                    foreach($item as $key2 => $item2){
                        if($item2){
                            echo $key2.': '.$item2.'&nbsp&nbsp&nbsp';
                        }
                    }
                }elseif($key=='recomendacoes_fiscais'){
                    foreach($item as $key2 => $item2){
                        if($item2){
                            echo $key2.': '.$item2.'&nbsp&nbsp&nbsp';
                        }
                    }
                }else{
                    echo $item;
                }
            ?>
        </td></tr>
    <?php endforeach; ?>
</table>
<?php elseif($act=='alt'): ?>
<form method="POST" action="../paginas/add.php?act=alt&pagina=produto" name="alt">
<table>
    <tr><th colspan="2">Detalhe do Produto</th></tr>
    <?php foreach($dados as $key => $item): ?>
    <tr><td><?= $key ?></td>
        <td>
            <?php
                if($key=='codigo_produto'){
                    echo '<input type=hidden name='.$key.' value="'.$item.'" >';
                    echo $item;
                }elseif($key=='dadosIbpt'){
                    foreach($item as $key2 => $item2){
                        if($item2){
                            echo $key2.': <input type=test name=dadosIbpt value="'.$item2.'"&nbsp&nbsp&nbsp';
                        }
                    }
                }elseif($key=='recomendacoes_fiscais'){
                    foreach($item as $key2 => $item2){
                        if($item2){
                            echo $key2.': <input type=test name=dadosIbpt value="'.$item2.'"&nbsp&nbsp&nbsp';
                        }
                    }
                }else{
                    echo '<input type=text size=55px name='.$key.' value="'.$item.'" >';
                }
            ?>
        </td></tr>
    <?php endforeach; ?>
</table>
<input type="submit" value="Salvar" /> 
</form>
<?php elseif($act=='list'): ?>
<div class="head">Lista de Produtos Cadastrados <span class="pag">(pág.<?= $dados->pagina ?>/<?= $dados->total_de_paginas ?>)</span>
</div>
<div class="total">total de registros <?= $dados->total_de_registros ?></div>
<table>
    <tr><th>Código</th><th>Descrição</th><th>Valor</th></tr>
    <?php 
    foreach($dados->produto_servico_cadastro as $produto): ?>
    <tr class="razaosocial" linha="<?= $produto->codigo_produto ?>"><td><?= $produto->codigo ?></td><td class="rs"><?= mb_strtoupper($produto->descricao,'utf-8') ?></td><td align=center ><?= number_format($produto->valor_unitario,'2',',','.') ?></td><td class="edicao"><img title="Altera" height="12px" src="../web/img/editar.png" codigo="<?= $produto->codigo_produto ?>" />-<img title="Exclui" height="12px" src="../web/img/excluir.png" codigo="<?= $produto->codigo_produto ?>" razao="<?= mb_strtoupper($produto->descricao,'utf-8') ?>" /></td></tr>
    <?php endforeach; ?>
</table>
<?php endif; ?>
</div>